## Préparer l’environnement

Nous importons les bibliothèques, définissons le lot et les sept tables sources, préparons les connexions MariaDB et les fonctions de lecture, de comparaison et d’enregistrement des résultats. Nous affichons aussi la version de MariaDB et sa collation.

Cela prépare les outils utilisés par les cellules suivantes et permet de comparer les valeurs sans confondre NULL, chaîne vide et espaces.

In [1]:
from pathlib import Path
from collections import Counter
from decimal import Decimal
import hashlib, json, csv, zlib, os
import pandas as pd
from sqlalchemy import create_engine, text
from IPython.display import display

ROOT = Path.cwd()
if not (ROOT / 'data').is_dir():
    ROOT = ROOT.parent
assert (ROOT / 'data/sources/crm/client.csv').is_file()
REPORTS = ROOT / 'reports'
REPORTS.mkdir(exist_ok=True)
BATCH = 'L-2026-10-01'
SOURCES = [('crm','client','crm_client'),('crm','contrat','crm_contrat'),
           ('crm','sinistre','crm_sinistre'),('crm','type_contrat','crm_type_contrat'),
           ('cif','clients','cif_clients'),('cif','compte','cif_compte'),('cif','pays','cif_pays')]
READER = create_engine('mysql+pymysql://reader:reader@mariadb:3306')
WRITER = create_engine('mysql+pymysql://root:root@mariadb:3306')
RESULTATS = {'perimetre':'Ingénieur qualité S1 — US-01/02/03','batch_id':BATCH,
             'notebook':'notebooks/S1_g02.ipynb','analyse_le':'2026-10-14'}

def query(sql, moteur=READER, **params):
    with moteur.connect() as cx:
        return pd.read_sql(text(sql), cx, params=params, coerce_float=False)

def colonnes(schema, table, moteur=READER):
    return query("""SELECT column_name, column_type, is_nullable
                    FROM information_schema.columns WHERE table_schema=:s AND table_name=:t
                    ORDER BY ordinal_position""", moteur, s=schema, t=table)

def lire_metier(schema, table, colonnes_metier, moteur=READER, lot=None, connexion=None):
    # MariaDB fournit les nombres et dates comme texte : pas de flottants implicites pour un INT nullable.
    # CAST conserve NULL, les vides, les espaces, les accents et l’échelle des DECIMAL.
    champs=', '.join(f'CAST(`{c}` AS CHAR CHARACTER SET utf8mb4) AS `{c}`' for c in colonnes_metier)
    q=f'SELECT {champs} FROM `{schema}`.`{table}`'
    params={}
    if lot is not None:
        q+=' WHERE _batch_id=:b';params['b']=lot
    if connexion is not None:
        return pd.read_sql(text(q),connexion,params=params,coerce_float=False).astype('string')
    return query(q,moteur,**params).astype('string')

def serialiser_ligne(row):
    # JSON distingue NULL, chaîne vide, blanc, texte "\\N", séparateurs et accents.
    valeurs=[None if pd.isna(v) else str(v) for v in row]
    return json.dumps(valeurs,ensure_ascii=False,separators=(',',':')).encode('utf-8')

def signatures(df):
    lignes=[serialiser_ligne(r) for r in df.itertuples(index=False,name=None)]
    multiset=Counter(lignes)
    empreinte=hashlib.sha256()
    for ligne in sorted(lignes):
        empreinte.update(len(ligne).to_bytes(8,'big'));empreinte.update(ligne)
    return {'lignes':len(lignes),'somme_controle':sum(zlib.crc32(l)&0xffffffff for l in lignes),
            'sha256':empreinte.hexdigest(),'multiset':multiset}

def public_signature(s):
    return {k:v for k,v in s.items() if k!='multiset'}

def enregistre():
    (REPORTS/'S1_ingenieur_qualite.json').write_text(json.dumps(RESULTATS,ensure_ascii=False,indent=2),encoding='utf-8')

display(query('SELECT VERSION() AS version, @@collation_server AS collation'))

def reconcilier(a, b):
    """Même prédicat pour la porte réelle et l’épreuve isolée."""
    return (a['lignes']==b['lignes'] and a['somme_controle']==b['somme_controle']
            and a['multiset']==b['multiset'])

                  version          collation
0  11.2.6-MariaDB-ubu2204  utf8mb4_nopad_bin

## Inventorier les sources

Nous relevons les colonnes, types, clés primaires et nombres de lignes des sept tables. Nous vérifions les clés, les en-têtes et effectifs des CSV, puis les droits de lecture du compte reader. Nous conservons les empreintes des fichiers et du contenu des sources.

Cela permet de connaître les données à ingérer et de disposer d’un état initial pour vérifier ensuite que les sources sont restées inchangées.

In [2]:
SOURCE_DATA, SOURCE_SIGNATURES, COLUMNS = {}, {}, {}
inventaire=[]; schemas=[]; fichiers=[]
for schema,table,cible in SOURCES:
    metadata=colonnes(schema,table)
    assert not metadata.empty, f'Table source absente : {schema}.{table}'
    cols=metadata.column_name.tolist();COLUMNS[cible]=cols
    metadata=metadata.copy();metadata.insert(0,'table_source',f'{schema}.{table}')
    schemas.extend(json.loads(metadata.to_json(orient='records')))
    pk=query("""SELECT column_name FROM information_schema.key_column_usage
                WHERE table_schema=:s AND table_name=:t AND constraint_name='PRIMARY'
                ORDER BY ordinal_position""",s=schema,t=table).column_name.tolist()
    df=lire_metier(schema,table,cols)
    n=int(query(f'SELECT COUNT(*) AS n FROM `{schema}`.`{table}`').n.iloc[0])
    assert n==len(df)>0, f'Source vide ou lecture incomplète : {schema}.{table}'
    path=ROOT/f'data/sources/{schema}/{table}.csv'
    with path.open(encoding='utf-8',newline='') as f:
        lecteur=csv.reader(f);entete=next(lecteur);n_csv=sum(1 for _ in lecteur)
    assert entete==cols and n_csv==n, f'En-tête ou effectif CSV/source différent pour {table}'
    fichiers.append({'fichier':str(path.relative_to(ROOT)),'lignes':n_csv,
                     'sha256':hashlib.sha256(path.read_bytes()).hexdigest()})
    null_pk=int(df[pk].isna().any(axis=1).sum()) if pk else None
    dup_pk=int(df[pk].duplicated().sum()) if pk else None
    inventaire.append({'source':schema,'table':table,'colonnes':len(cols),'lignes':n,
                       'cle_primaire':', '.join(pk) or None,'nuls_pk':null_pk,'doublons_pk':dup_pk})
    SOURCE_DATA[cible]=df;SOURCE_SIGNATURES[cible]=signatures(df)

privileges=query("""SELECT table_schema,privilege_type FROM information_schema.schema_privileges
                    WHERE grantee=:g ORDER BY table_schema,privilege_type""", WRITER,g="'reader'@'%'")
globaux=query("SELECT privilege_type FROM information_schema.user_privileges WHERE grantee=:g",WRITER,g="'reader'@'%'")
tables_priv=query("SELECT table_schema,table_name,privilege_type FROM information_schema.table_privileges WHERE grantee=:g",WRITER,g="'reader'@'%'")
assert set(zip(privileges.table_schema,privileges.privilege_type))=={('cif','SELECT'),('crm','SELECT')}
assert set(globaux.privilege_type)<= {'USAGE'} and tables_priv.empty, 'Droits reader inattendus'
display(pd.DataFrame(inventaire));display(pd.DataFrame(schemas));display(privileges)
print('Tables sans clé primaire :',[f"{r['source']}.{r['table']}" for r in inventaire if not r['cle_primaire']])
RESULTATS['inventaire']=inventaire;RESULTATS['colonnes_sql']=schemas;RESULTATS['fichiers_sources']=fichiers
RESULTATS['droits_reader']=json.loads(privileges.to_json(orient='records'))
RESULTATS['source_avant']={t:public_signature(s) for t,s in SOURCE_SIGNATURES.items()}
enregistre()

  source         table  colonnes  lignes cle_primaire  nuls_pk  doublons_pk
0    crm        client        13  100000    client_id        0            0
1    crm       contrat         9  100000   contrat_id        0            0
2    crm      sinistre        10  100000  sinistre_id        0            0
3    crm  type_contrat         3      12    code_type        0            0
4    cif       clients        10   40000      column0        0            0
5    cif        compte         4   45000      column0        0            0
6    cif          pays         2     250    code_pays        0            0

        table_source               column_name    column_type is_nullable
0         crm.client                 client_id    varchar(12)          NO
1         crm.client             type_personne    varchar(20)         YES
2         crm.client                       nom    varchar(80)         YES
3         crm.client                    prenom    varchar(80)         YES
4         crm.client            raison_sociale   varchar(120)         YES
5         crm.client            date_naissance           date         YES
6         crm.client                   adresse   varchar(120)         YES
7         crm.client                        cp    varchar(10)         YES
8         crm.client                     ville    varchar(80)         YES
9         crm.client                      pays    varchar(10)         YES
10        crm.client                 telephone    varchar(25)         YES
11        crm.client                     email   varchar(120)         YES
12        crm.client             date_creation           date         YES
13       crm.contrat                contrat_id    varchar(12)          NO
14       crm.contrat           souscripteur_id    varchar(12)         YES
15       crm.contrat                 assure_id    varchar(12)         YES
16       crm.contrat                 code_type    varchar(10)         YES
17       crm.contrat                date_debut           date         YES
18       crm.contrat                  date_fin           date         YES
19       crm.contrat       duree_garantie_mois        int(11)         YES
20       crm.contrat            prime_annuelle  decimal(10,2)         YES
21       crm.contrat  date_derniere_cotisation           date         YES
22      crm.sinistre               sinistre_id    varchar(12)          NO
23      crm.sinistre                contrat_id    varchar(12)         YES
24      crm.sinistre           date_survenance           date         YES
25      crm.sinistre          date_declaration           date         YES
26      crm.sinistre             type_sinistre    varchar(40)         YES
27      crm.sinistre            montant_estime  decimal(12,2)         YES
28      crm.sinistre          adresse_sinistre   varchar(160)         YES
29      crm.sinistre               cp_sinistre    varchar(10)         YES
30      crm.sinistre            ville_sinistre    varchar(80)         YES
31      crm.sinistre              canal_saisie    varchar(30)         YES
32  crm.type_contrat                 code_type    varchar(10)          NO
33  crm.type_contrat                   libelle    varchar(80)          NO
34  crm.type_contrat                   branche    varchar(20)          NO
35       cif.clients                   column0    varchar(10)          NO
36       cif.clients                   column1   varchar(120)         YES
37       cif.clients                   column2    varchar(80)         YES
38       cif.clients                   column3    varchar(10)         YES
39       cif.clients                   column4   varchar(120)         YES
40       cif.clients                   column5    varchar(10)         YES
41       cif.clients                   column6    varchar(80)         YES
42       cif.clients                   column7     varchar(5)         YES
43       cif.clients                   column8    varchar(25)         YES
44       cif.clients                   column9   varchar(120)         YES
45        cif.compte                   column0    varchar(12)          NO
46        cif.compte                   column1    varchar(10)         YES
47        cif.compte                   column2           date         YES
48        cif.compte                   column3        char(1)         YES
49          cif.pays                 code_pays        char(2)          NO
50          cif.pays                  nom_pays    varchar(80)          NO

  table_schema privilege_type
0          cif         SELECT
1          crm         SELECT

Tables sans clé primaire : []

## Alimenter bronze

Nous copions les sept tables sources dans bronze pour le lot courant, en ajoutant le lot, le système source, l’horodatage et l’empreinte de chaque ligne. La cellule vérifie les tables existantes et le contenu du lot avant de le remplacer, puis réalise l’ingestion dans une transaction protégée par un verrou.

Cela crée une copie fidèle et identifiable des données, avec une relance limitée au même lot et une ingestion cohérente des sept tables.

In [3]:
def ingester():
    verrou='assurconnect:bronze:'+BATCH
    with WRITER.connect() as cx:
        assert cx.execute(text('SELECT GET_LOCK(:v,0)'),{'v':verrou}).scalar()==1, 'Ingestion de ce lot déjà en cours'
        cx.commit()
        try:
            with cx.begin():
                # Toutes les vérifications précèdent les suppressions ; aucune table source n’est écrite.
                for schema,table,cible in SOURCES:
                    attendu=COLUMNS[cible]
                    bronze_cols=colonnes('bronze',cible,WRITER).column_name.tolist()
                    assert [c for c in bronze_cols if c!='bronze_row_id' and not c.startswith('_')]==attendu
                    existant=lire_metier('bronze',cible,attendu,WRITER,lot=BATCH,connexion=cx)
                    if len(existant):
                        assert signatures(existant)['multiset']==SOURCE_SIGNATURES[cible]['multiset'], f'Lot bronze existant divergent : {cible}'
                cx.execute(text("INSERT INTO dq.lot_ingestion(batch_id,statut) VALUES(:b,'EN_COURS') ON DUPLICATE KEY UPDATE statut='EN_COURS',finished_at=NULL"),{'b':BATCH})
                for schema,table,cible in SOURCES:
                    df=SOURCE_DATA[cible].copy()
                    hashes=[hashlib.sha256(serialiser_ligne(r)).hexdigest()[:16] for r in df.itertuples(index=False,name=None)]
                    df['_batch_id']=BATCH;df['_source_system']=schema;df['_row_hash']=hashes
                    df=df.astype(object).where(df.notna(),None)
                    cx.execute(text(f'DELETE FROM bronze.`{cible}` WHERE _batch_id=:b'),{'b':BATCH})
                    # _ingested_at est fourni par DEFAULT CURRENT_TIMESTAMP du schéma existant.
                    df.to_sql(cible,cx,schema='bronze',if_exists='append',index=False,method='multi',chunksize=1000)
                cx.execute(text("UPDATE dq.lot_ingestion SET statut='TERMINE',finished_at=NOW() WHERE batch_id=:b"),{'b':BATCH})
        finally:
            cx.execute(text('SELECT RELEASE_LOCK(:v)'),{'v':verrou});cx.commit()

ingester()
RESULTATS['ingestion']={'batch_id':BATCH,'tables':7,'lignes':sum(len(d) for d in SOURCE_DATA.values()),
                       'transaction':'sept tables et lot','statut':'TERMINE','sources_modifiees':False}
display(query('SELECT batch_id,statut,started_at,finished_at FROM dq.lot_ingestion WHERE batch_id=:b',WRITER,b=BATCH))
print('Lignes ingérées :',RESULTATS['ingestion']['lignes'])
enregistre()

       batch_id   statut          started_at         finished_at
0  L-2026-10-01  TERMINE 2026-10-14 13:26:50 2026-10-14 13:37:34

Lignes ingérées : 385262

## Vérifier la porte B

Nous comparons les nombres de lignes, les sommes de contrôle et le contenu complet des sources avec bronze. Nous contrôlons aussi les quatre métadonnées et l’empreinte de chaque ligne, puis enregistrons les mesures RQ-021 et RQ-022 dans dq.dq_history.

Cela vérifie que l’ingestion n’a perdu ni modifié les données et conserve les résultats des contrôles. La cellule échoue si la porte B est non conforme.

In [4]:
def porte_b(historiser=True):
    preuves=[];meta_preuves=[];mesures=[]
    for schema,table,cible in SOURCES:
        src=lire_metier(schema,table,COLUMNS[cible])
        assert signatures(src)['multiset']==SOURCE_SIGNATURES[cible]['multiset'], f'Source modifiée depuis inventaire : {schema}.{table}'
        bronze=lire_metier('bronze',cible,COLUMNS[cible],WRITER,lot=BATCH)
        a,b=signatures(src),signatures(bronze)
        conforme=reconcilier(a,b)
        preuves.append({'table_bronze':cible,'lignes_source':a['lignes'],'lignes_bronze':b['lignes'],
                        'ecart_comptage':b['lignes']-a['lignes'],'somme_source':a['somme_controle'],
                        'somme_bronze':b['somme_controle'],'ecart_somme':b['somme_controle']-a['somme_controle'],
                        'contenu_exact_identique':a['multiset']==b['multiset'],'sha256':b['sha256'],'conforme':conforme})
        metadonnees=['_batch_id','_source_system','_ingested_at','_row_hash']
        controle=lire_metier('bronze',cible,COLUMNS[cible]+metadonnees,WRITER,lot=BATCH)
        hashes_attendus=pd.Series([hashlib.sha256(serialiser_ligne(r)).hexdigest()[:16]
                                  for r in controle[COLUMNS[cible]].itertuples(index=False,name=None)],
                                 index=controle.index,dtype='string')
        invalides=(controle[metadonnees].isna().any(axis=1)
                   | controle[metadonnees].eq('').any(axis=1)
                   | ~controle._source_system.eq(schema).fillna(False)
                   | ~controle._row_hash.eq(hashes_attendus).fillna(False))
        n,ko=len(controle),int(invalides.sum())
        meta_preuves.append({'table_bronze':cible,'testees':n,'echecs':ko,'conforme':ko==0})
        mesures.extend([('RQ-021',cible,1,int(not conforme)),('RQ-022',cible,n,ko)])
    # Historiser uniquement la porte réelle ; une épreuve sur copie n’appelle jamais cette fonction.
    if historiser:
        with WRITER.begin() as cx:
            for rq,table,n,ko in mesures:
                params={'b':BATCH,'r':rq,'t':table,'n':n,'ko':ko}
                cx.execute(text("DELETE FROM dq.dq_history WHERE batch_id=:b AND couche='BRONZE' AND rule_id=:r AND table_cible=:t"),params)
                cx.execute(text("INSERT INTO dq.dq_history(batch_id,couche,rule_id,table_cible,nb_testees,nb_echecs) VALUES(:b,'BRONZE',:r,:t,:n,:ko)"),params)
    RESULTATS['porte_B']=preuves;RESULTATS['RQ_022']=meta_preuves
    display(pd.DataFrame(preuves));display(pd.DataFrame(meta_preuves))
    assert all(p['conforme'] for p in preuves+meta_preuves), 'Porte B refusée'
    return preuves

premiere_porte=porte_b()
RESULTATS['historique_unites']={'RQ-021':'un contrôle global par table','RQ-022':'une vérification de métadonnées par ligne'}
display(query("SELECT couche,rule_id,table_cible,nb_testees,nb_echecs,taux_conformite FROM dq.dq_history WHERE batch_id=:b ORDER BY rule_id,table_cible",WRITER,b=BATCH))
enregistre()

,table_bronze,lignes_source,lignes_bronze,ecart_comptage,somme_source,somme_bronze,ecart_somme,contenu_exact_identique,sha256,conforme
0,crm_client,100000,100000,0,214701936373892,214701936373892,0,True,e9b49de45147c03094fce2ce25f07a21d4bf5a2cfa0842...,True
1,crm_contrat,100000,100000,0,214920543380008,214920543380008,0,True,4aa3d6ea1684bd73e428eda427f392da71154c79cd8a67...,True
2,crm_sinistre,100000,100000,0,214256364507763,214256364507763,0,True,20c28ec5b2930473022fbaf620f4e231502fea36049a9d...,True
3,crm_type_contrat,12,12,0,25049111003,25049111003,0,True,8b3ded94d4686fe65cc9d0a72527247272234f687e32fc...,True
4,cif_clients,40000,40000,0,85743772090414,85743772090414,0,True,846ce93845d91bb1000e29faaa507cf59992cbad93db14...,True
5,cif_compte,45000,45000,0,96942383526087,96942383526087,0,True,a4367d053addd21048ced2cebac3684932facef42ee36a...,True
6,cif_pays,250,250,0,548069437591,548069437591,0,True,bc499447f3406b56bc373aed7e127263c7d27c5d293607...,True

       table_bronze  testees  echecs  conforme
0        crm_client   100000       0      True
1       crm_contrat   100000       0      True
2      crm_sinistre   100000       0      True
3  crm_type_contrat       12       0      True
4       cif_clients    40000       0      True
5        cif_compte    45000       0      True
6          cif_pays      250       0      True

    couche rule_id       table_cible  nb_testees  nb_echecs taux_conformite
0   BRONZE  RQ-021       cif_clients           1          0         100.000
1   BRONZE  RQ-021        cif_compte           1          0         100.000
2   BRONZE  RQ-021          cif_pays           1          0         100.000
3   BRONZE  RQ-021        crm_client           1          0         100.000
4   BRONZE  RQ-021       crm_contrat           1          0         100.000
5   BRONZE  RQ-021      crm_sinistre           1          0         100.000
6   BRONZE  RQ-021  crm_type_contrat           1          0         100.000
7   BRONZE  RQ-022       cif_clients       40000          0         100.000
8   BRONZE  RQ-022        cif_compte       45000          0         100.000
9   BRONZE  RQ-022          cif_pays         250          0         100.000
10  BRONZE  RQ-022        crm_client      100000          0         100.000
11  BRONZE  RQ-022       crm_contrat      100000          0         100.000
12  BRONZE  RQ-022      crm_sinistre      100000          0         100.000
13  BRONZE  RQ-022  crm_type_contrat          12          0         100.000

## Tester la relance

Nous relançons l’ingestion et la porte B, puis comparons les volumes et le contenu avant et après. Nous vérifions les doublons sur les clés métier et la conservation des autres lots lorsqu’ils existent.

Cela démontre qu’exécuter à nouveau le même lot n’ajoute pas de doublons et conserve les valeurs métier, même si les identifiants techniques et horodatages changent.

In [5]:
avant={p['table_bronze']:(p['lignes_bronze'],p['sha256']) for p in premiere_porte}
autres_lots={c:query(f'SELECT * FROM bronze.`{c}` WHERE _batch_id<>:b',WRITER,b=BATCH).to_json(orient='split',date_format='iso') for _,_,c in SOURCES}
ingester()
deuxieme_porte=porte_b()
apres={p['table_bronze']:(p['lignes_bronze'],p['sha256']) for p in deuxieme_porte}
assert avant==apres, 'Relance non idempotente'
assert all(query(f'SELECT * FROM bronze.`{c}` WHERE _batch_id<>:b',WRITER,b=BATCH).to_json(orient='split',date_format='iso')==autres_lots[c] for _,_,c in SOURCES)
doublons=[]
for schema,table,cible in SOURCES:
    pk=[x.strip() for x in next(r['cle_primaire'] for r in inventaire if r['source']==schema and r['table']==table).split(',')]
    df=lire_metier('bronze',cible,COLUMNS[cible],WRITER,lot=BATCH)
    doublons.append({'table_bronze':cible,'doublons_cles_metier':int(df[pk].duplicated().sum())})
assert all(r['doublons_cles_metier']==0 for r in doublons)
RESULTATS['relance']={'contenu_et_volumes_identiques':True,'autres_lots_inchanges':True,
                     'doublons':doublons,'doublons_ajoutes':0}
display(pd.DataFrame(doublons))
enregistre()

,table_bronze,lignes_source,lignes_bronze,ecart_comptage,somme_source,somme_bronze,ecart_somme,contenu_exact_identique,sha256,conforme
0,crm_client,100000,100000,0,214701936373892,214701936373892,0,True,e9b49de45147c03094fce2ce25f07a21d4bf5a2cfa0842...,True
1,crm_contrat,100000,100000,0,214920543380008,214920543380008,0,True,4aa3d6ea1684bd73e428eda427f392da71154c79cd8a67...,True
2,crm_sinistre,100000,100000,0,214256364507763,214256364507763,0,True,20c28ec5b2930473022fbaf620f4e231502fea36049a9d...,True
3,crm_type_contrat,12,12,0,25049111003,25049111003,0,True,8b3ded94d4686fe65cc9d0a72527247272234f687e32fc...,True
4,cif_clients,40000,40000,0,85743772090414,85743772090414,0,True,846ce93845d91bb1000e29faaa507cf59992cbad93db14...,True
5,cif_compte,45000,45000,0,96942383526087,96942383526087,0,True,a4367d053addd21048ced2cebac3684932facef42ee36a...,True
6,cif_pays,250,250,0,548069437591,548069437591,0,True,bc499447f3406b56bc373aed7e127263c7d27c5d293607...,True

       table_bronze  testees  echecs  conforme
0        crm_client   100000       0      True
1       crm_contrat   100000       0      True
2      crm_sinistre   100000       0      True
3  crm_type_contrat       12       0      True
4       cif_clients    40000       0      True
5        cif_compte    45000       0      True
6          cif_pays      250       0      True

       table_bronze  doublons_cles_metier
0        crm_client                     0
1       crm_contrat                     0
2      crm_sinistre                     0
3  crm_type_contrat                     0
4       cif_clients                     0
5        cif_compte                     0
6          cif_pays                     0

## Tester la détection d’un écart

Nous copions les clients bronze du lot courant dans une table de test, modifions une valeur et appliquons le même contrôle de réconciliation. Nous supprimons ensuite la copie et vérifions que l’historique est resté identique.

Cela démontre que le contrôle détecte une modification même lorsque le nombre de lignes reste identique, sans altérer les données réelles ni enregistrer l’échec du test dans leur historique.

In [6]:
COPY='crm_client_test_s1_g02'
exists=int(query("SELECT COUNT(*) AS n FROM information_schema.tables WHERE table_schema='bronze' AND table_name=:t",WRITER,t=COPY).n.iloc[0])
assert exists==0, 'Copie de test préexistante : ne pas l’écraser'
history_before=query('SELECT * FROM dq.dq_history ORDER BY id',WRITER).to_json(orient='split',date_format='iso')
created=False
try:
    with WRITER.begin() as cx:
        cx.execute(text(f'CREATE TABLE bronze.`{COPY}` LIKE bronze.crm_client'));created=True
        cx.execute(text(f'INSERT INTO bronze.`{COPY}` SELECT * FROM bronze.crm_client WHERE _batch_id=:b'),{'b':BATCH})
    copie=lire_metier('bronze',COPY,COLUMNS['crm_client'],WRITER,lot=BATCH)
    assert signatures(copie)['multiset']==SOURCE_SIGNATURES['crm_client']['multiset']
    with WRITER.begin() as cx:
        cx.execute(text(f"UPDATE bronze.`{COPY}` SET pays=CONCAT(COALESCE(pays,''),'__EPREUVE_S1__') WHERE _batch_id=:b ORDER BY bronze_row_id LIMIT 1"),{'b':BATCH})
    alteree=signatures(lire_metier('bronze',COPY,COLUMNS['crm_client'],WRITER,lot=BATCH))
    source=SOURCE_SIGNATURES['crm_client']
    conforme=reconcilier(source,alteree)
    assert not conforme, 'Écart non détecté'
    RESULTATS['epreuve_copie']={'table':COPY,'lignes':alteree['lignes'],'ecart_comptage':alteree['lignes']-source['lignes'],
                              'ecart_somme':alteree['somme_controle']-source['somme_controle'],
                              'contenu_exact_identique':False,'porte_accepte':conforme,'historisee':False}
finally:
    if created:
        with WRITER.begin() as cx:cx.execute(text(f'DROP TABLE bronze.`{COPY}`'))
assert int(query("SELECT COUNT(*) AS n FROM information_schema.tables WHERE table_schema='bronze' AND table_name=:t",WRITER,t=COPY).n.iloc[0])==0
assert query('SELECT * FROM dq.dq_history ORDER BY id',WRITER).to_json(orient='split',date_format='iso')==history_before
RESULTATS['epreuve_copie']['copie_supprimee']=True
display(pd.DataFrame([RESULTATS['epreuve_copie']]))
enregistre()

,table,lignes,ecart_comptage,ecart_somme,contenu_exact_identique,porte_accepte,historisee,copie_supprimee
0,crm_client_test_s1_g02,100000,0,-3465902982,False,False,False,True

## Vérifier les conversions

Nous lisons un montant réel avec et sans conversion en flottant, puis comparons les représentations et leurs sommes de contrôle. Nous testons aussi la distinction entre NULL, vide, blanc, accents et textes contenant des séparateurs.

Cela montre pourquoi une lecture exacte des décimales et une sérialisation non ambiguë sont nécessaires pour éviter les faux écarts et conserver les différences entre les valeurs.

In [7]:
sql="SELECT prime_annuelle FROM crm.contrat WHERE prime_annuelle IS NOT NULL AND MOD(prime_annuelle*100,10)=0 ORDER BY contrat_id LIMIT 1"
with READER.connect() as cx:
    mauvais=pd.read_sql(text(sql),cx,coerce_float=True).prime_annuelle.iloc[0]
    exact=pd.read_sql(text(sql),cx,coerce_float=False).prime_annuelle.iloc[0]
assert isinstance(exact,Decimal) and str(mauvais)!=str(exact), 'Cas décimal illustratif non trouvé'
valeurs=[[None],[''],[' '],[r'\N'],['a|b'],['a','b'],['é'],['e']]
encodages=[serialiser_ligne(v) for v in valeurs]
assert len(set(encodages))==len(valeurs)
# Un même montant doit produire la même représentation dans les deux couches.
reference=signatures(pd.DataFrame({'montant':[str(exact)]},dtype='string'))
flottante=signatures(pd.DataFrame({'montant':[str(mauvais)]},dtype='string'))
exacte=signatures(pd.DataFrame({'montant':[str(exact)]},dtype='string'))
assert not reconcilier(reference,flottante) and reconcilier(reference,exacte)
RESULTATS['conversion']={'cas':'montant réel de crm.contrat','lecture_flottante':str(mauvais),
                        'lecture_exacte':str(exact),'type_exact':type(exact).__name__,
                        'presentation_flottante_perdue':True,
                        'somme_reference':reference['somme_controle'],'somme_flottante':flottante['somme_controle'],
                        'somme_exacte':exacte['somme_controle'],'faux_ecart_flottant_detecte':True,'correction':'coerce_float=False et conversion SQL explicite en texte',
                        'distinctions_synthetiques_preservees':True}
display(pd.DataFrame([RESULTATS['conversion']]))
enregistre()

,cas,lecture_flottante,lecture_exacte,type_exact,presentation_flottante_perdue,somme_reference,somme_flottante,somme_exacte,faux_ecart_flottant_detecte,correction,distinctions_synthetiques_preservees
0,montant réel de crm.contrat,184.1,184.10,Decimal,True,3810312921,3371018125,3810312921,True,coerce_float=False et conversion SQL explicite...,True

## Vérifier les résultats finaux

Nous contrôlons à nouveau la porte B, les empreintes des sources et des sept CSV, ainsi que les quatorze mesures attendues dans dq.dq_history. Nous enregistrons la synthèse finale dans le rapport JSON (gardé en local).

Cela confirme que les épreuves ont laissé les données réelles intactes et que les preuves des trois stories techniques S1 sont disponibles.

In [8]:
porte_finale=porte_b(historiser=False)
for schema,table,cible in SOURCES:
    assert signatures(lire_metier(schema,table,COLUMNS[cible]))['multiset']==SOURCE_SIGNATURES[cible]['multiset']
for f in RESULTATS['fichiers_sources']:
    assert hashlib.sha256((ROOT/f['fichier']).read_bytes()).hexdigest()==f['sha256']
history=query("""SELECT couche,rule_id,table_cible,nb_testees,nb_echecs,taux_conformite
                 FROM dq.dq_history WHERE batch_id=:b AND couche='BRONZE' AND rule_id IN ('RQ-021','RQ-022')
                 ORDER BY rule_id,table_cible""",WRITER,b=BATCH)
assert len(history)==14 and history.nb_echecs.eq(0).all() and history.taux_conformite.eq(Decimal('100.000')).all()
assert set(zip(history.rule_id,history.table_cible))=={(rq,c) for rq in ['RQ-021','RQ-022'] for _,_,c in SOURCES}
RESULTATS['historique']=json.loads(history.to_json(orient='records'))
RESULTATS['verification_finale']={'sources_inchangees':True,'csv_inchanges':True,'porte_B_conforme':True,
                               'mesures_historiques':14,'erreurs':0,'stories_terminees':['US-01','US-02','US-03'],
                               'seance_S1_globale_terminee':False}
display(history)
enregistre()
print('US-01, US-02, US-03 démontrées — aucune tâche d’un autre rôle réalisée.')

,table_bronze,lignes_source,lignes_bronze,ecart_comptage,somme_source,somme_bronze,ecart_somme,contenu_exact_identique,sha256,conforme
0,crm_client,100000,100000,0,214701936373892,214701936373892,0,True,e9b49de45147c03094fce2ce25f07a21d4bf5a2cfa0842...,True
1,crm_contrat,100000,100000,0,214920543380008,214920543380008,0,True,4aa3d6ea1684bd73e428eda427f392da71154c79cd8a67...,True
2,crm_sinistre,100000,100000,0,214256364507763,214256364507763,0,True,20c28ec5b2930473022fbaf620f4e231502fea36049a9d...,True
3,crm_type_contrat,12,12,0,25049111003,25049111003,0,True,8b3ded94d4686fe65cc9d0a72527247272234f687e32fc...,True
4,cif_clients,40000,40000,0,85743772090414,85743772090414,0,True,846ce93845d91bb1000e29faaa507cf59992cbad93db14...,True
5,cif_compte,45000,45000,0,96942383526087,96942383526087,0,True,a4367d053addd21048ced2cebac3684932facef42ee36a...,True
6,cif_pays,250,250,0,548069437591,548069437591,0,True,bc499447f3406b56bc373aed7e127263c7d27c5d293607...,True

       table_bronze  testees  echecs  conforme
0        crm_client   100000       0      True
1       crm_contrat   100000       0      True
2      crm_sinistre   100000       0      True
3  crm_type_contrat       12       0      True
4       cif_clients    40000       0      True
5        cif_compte    45000       0      True
6          cif_pays      250       0      True

    couche rule_id       table_cible  nb_testees  nb_echecs taux_conformite
0   BRONZE  RQ-021       cif_clients           1          0         100.000
1   BRONZE  RQ-021        cif_compte           1          0         100.000
2   BRONZE  RQ-021          cif_pays           1          0         100.000
3   BRONZE  RQ-021        crm_client           1          0         100.000
4   BRONZE  RQ-021       crm_contrat           1          0         100.000
5   BRONZE  RQ-021      crm_sinistre           1          0         100.000
6   BRONZE  RQ-021  crm_type_contrat           1          0         100.000
7   BRONZE  RQ-022       cif_clients       40000          0         100.000
8   BRONZE  RQ-022        cif_compte       45000          0         100.000
9   BRONZE  RQ-022          cif_pays         250          0         100.000
10  BRONZE  RQ-022        crm_client      100000          0         100.000
11  BRONZE  RQ-022       crm_contrat      100000          0         100.000
12  BRONZE  RQ-022      crm_sinistre      100000          0         100.000
13  BRONZE  RQ-022  crm_type_contrat          12          0         100.000

US-01, US-02, US-03 démontrées — aucune tâche d’un autre rôle réalisée.