## Préparer l’environnement

Nous importons les bibliothèques nécessaires à l’analyse de qualité, définissons l’identifiant du lot étudié et préparons les connexions à MariaDB. Nous définissons également une fonction query() pour exécuter les requêtes SQL et récupérer leurs résultats sous forme de DataFrame pandas.

Cette préparation permet aux cellules suivantes d’interroger les données de Bronze et d’effectuer les contrôles de qualité sans modifier les données sources.

In [4]:
import pandas as pd
from sqlalchemy import create_engine, text

BATCH = "L-2026-10-01"

READER = create_engine(
    "mysql+pymysql://reader:reader@mariadb:3306"
)

WRITER = create_engine(
    "mysql+pymysql://root:root@mariadb:3306"
)

def query(sql, moteur=READER, **params):
    with moteur.connect() as cx:
        return pd.read_sql(
            text(sql),
            cx,
            params=params,
            coerce_float=False
        )

## Vérifier la disponibilité des dates de naissance

Nous comptons le nombre de clients présents dans la table Bronze et le nombre de clients pour lesquels une date de naissance est renseignée.

Ce contrôle permet d’évaluer la disponibilité de cette donnée indispensable au calcul de l’âge du souscripteur au début du contrat. Il ne vérifie pas encore si les dates sont valides ni si les contrats respectent la règle RQ-002.

In [5]:
display(query("""
SELECT
    COUNT(*) AS total_clients,
    COUNT(date_naissance) AS clients_avec_date_naissance
FROM bronze.crm_client
WHERE _batch_id = :b
""", WRITER, b=BATCH))

   total_clients  clients_avec_date_naissance
0         100000                        95723

## Relier les contrats à leurs souscripteurs
Nous rapprochons les contrats de leurs souscripteurs à l’aide de l’identifiant client. La jointure permet de récupérer la date de naissance du souscripteur et la date de début du contrat, tout en conservant les contrats pour lesquels aucune correspondance client n’est trouvée.

Ce contrôle prépare les données nécessaires au calcul de l’âge à la souscription et permet d’identifier les informations manquantes.

In [6]:
# %% Bloc 3 — Relier les contrats à leurs souscripteurs

contrats = query("""
SELECT
    c.contrat_id,
    c.souscripteur_id,
    c.date_debut,
    cl.date_naissance
FROM bronze.crm_contrat AS c
LEFT JOIN bronze.crm_client AS cl
    ON c.souscripteur_id = cl.client_id
   AND cl._batch_id = :b
WHERE c._batch_id = :b
""", WRITER, b=BATCH)

print(f"Nombre de contrats : {len(contrats)}")
print(f"Date de naissance renseignée : {contrats['date_naissance'].notna().sum()}")
print(f"Date de naissance absente : {contrats['date_naissance'].isna().sum()}")

display(contrats.head(10))

Nombre de contrats : 100000
Date de naissance renseignée : 92996
Date de naissance absente : 7004

  contrat_id souscripteur_id  date_debut date_naissance
0  CT0000001         A-18356  2009-08-10     1946-01-12
1  CT0000002         H-22766  2009-08-22     1954-04-01
2  CT0000003         H-35362  2011-04-05     1956-04-27
3  CT0000004         A-28218  2012-09-23     1975-10-25
4  CT0000005         A-34113  2014-01-02     1973-12-25
5  CT0000006         H-26653  2014-01-02           None
6  CT0000007         H-27488  2014-01-02     1951-12-22
7  CT0000008          H-3365  2014-01-02     1968-01-06
8  CT0000009         S-12253  2014-01-02     1976-11-16
9  CT0000010          H-1304  2014-01-03     1966-02-09

## Calculer l’âge à la souscription

Nous calculons l’âge du souscripteur à la date de début du contrat. Le calcul tient compte du jour et du mois de naissance afin de ne pas surestimer l’âge avant l’anniversaire.

Lorsque la date de naissance ou la date de début du contrat est absente ou invalide, l’âge n’est pas calculé. Ces situations sont conservées afin de pouvoir être analysées séparément.

In [7]:
# %% Bloc 4 — Calculer l’âge à la souscription

contrats["date_debut"] = pd.to_datetime(
    contrats["date_debut"], errors="coerce"
)

contrats["date_naissance"] = pd.to_datetime(
    contrats["date_naissance"], errors="coerce"
)

dates_valides = (
    contrats["date_debut"].notna()
    & contrats["date_naissance"].notna()
)

contrats["age_debut"] = pd.Series(
    float("nan"), index=contrats.index
)

contrats.loc[dates_valides, "age_debut"] = (
    contrats.loc[dates_valides, "date_debut"].dt.year
    - contrats.loc[dates_valides, "date_naissance"].dt.year
    - (
        (
            contrats.loc[dates_valides, "date_debut"].dt.month
            < contrats.loc[dates_valides, "date_naissance"].dt.month
        )
        |
        (
            (
                contrats.loc[dates_valides, "date_debut"].dt.month
                == contrats.loc[dates_valides, "date_naissance"].dt.month
            )
            &
            (
                contrats.loc[dates_valides, "date_debut"].dt.day
                < contrats.loc[dates_valides, "date_naissance"].dt.day
            )
        )
    ).astype(int)
)

print(f"Contrats analysés : {len(contrats)}")
print(f"Âge calculable : {contrats['age_debut'].notna().sum()}")
print(f"Âge non calculable : {contrats['age_debut'].isna().sum()}")

display(
    contrats[
        [
            "contrat_id",
            "souscripteur_id",
            "date_debut",
            "date_naissance",
            "age_debut",
        ]
    ].head(20)
)

Contrats analysés : 100000
Âge calculable : 92996
Âge non calculable : 7004

   contrat_id souscripteur_id date_debut date_naissance  age_debut
0   CT0000001         A-18356 2009-08-10     1946-01-12       63.0
1   CT0000002         H-22766 2009-08-22     1954-04-01       55.0
2   CT0000003         H-35362 2011-04-05     1956-04-27       54.0
3   CT0000004         A-28218 2012-09-23     1975-10-25       36.0
4   CT0000005         A-34113 2014-01-02     1973-12-25       40.0
5   CT0000006         H-26653 2014-01-02            NaT        NaN
6   CT0000007         H-27488 2014-01-02     1951-12-22       62.0
7   CT0000008          H-3365 2014-01-02     1968-01-06       45.0
8   CT0000009         S-12253 2014-01-02     1976-11-16       37.0
9   CT0000010          H-1304 2014-01-03     1966-02-09       47.0
10  CT0000011         H-26699 2014-01-03     1962-12-31       51.0
11  CT0000012         A-40684 2014-01-04     1991-09-14       22.0
12  CT0000013         H-12800 2014-01-04     1989-12-17       24.0
13  CT0000014         H-14819 2014-01-04     1950-04-16       63.0
14  CT0000015          S-2208 2014-01-04            NaT        NaN
15  CT0000016         A-19637 2014-01-05     1960-11-13       53.0
16  CT0000017         A-36276 2014-01-06     1939-02-01       74.0
17  CT0000018         H-16110 2014-01-07     1967-02-14       46.0
18  CT0000019         A-35836 2014-01-08     1992-03-06       21.0
19  CT0000020          H-4992 2014-01-09     1946-09-23       67.0

## Comparer les règles de calcul de l’âge

Nous comparons l’âge calculé à la date de début du contrat à l’âge calculé à une date de référence fixe. Nous examinons ensuite les contrats pour lesquels le classement par rapport au seuil de 18 ans diffère entre les deux méthodes.

La date de référence doit être explicitement définie afin de garantir la reproductibilité de l’analyse. Les contrats dont l’âge ne peut pas être calculé sont exclus de cette comparaison et comptabilisés séparément.

In [8]:
# %% Bloc 5 — Comparer les règles de calcul de l’âge

# Fecha fija para que los resultados sean reproducibles.
# Confirma que esta fecha corresponde a la definida en vuestro proyecto.
DATE_REF = pd.Timestamp("2026-10-01")

c = contrats[
    contrats["age_debut"].notna()
    & contrats["date_naissance"].notna()
].copy()

c["age_reference"] = (
    DATE_REF.year
    - c["date_naissance"].dt.year
    - (
        (
            DATE_REF.month < c["date_naissance"].dt.month
        )
        |
        (
            (DATE_REF.month == c["date_naissance"].dt.month)
            & (DATE_REF.day < c["date_naissance"].dt.day)
        )
    ).astype(int)
)

mineur_signature = c["age_debut"] < 18
mineur_reference = c["age_reference"] < 18

changement = mineur_signature != mineur_reference

print(f"Contrats avec âge calculable : {len(c)}")
print(f"Mineurs à la signature : {int(mineur_signature.sum())}")
print(f"Mineurs à la date de référence : {int(mineur_reference.sum())}")
print(f"Classement différent : {int(changement.sum())}")
print(f"Âge non calculable : {int(contrats['age_debut'].isna().sum())}")

display(
    c.loc[
        changement,
        [
            "contrat_id",
            "souscripteur_id",
            "date_naissance",
            "date_debut",
            "age_debut",
            "age_reference",
        ],
    ].head(20)
)

Contrats avec âge calculable : 92996
Mineurs à la signature : 301
Mineurs à la date de référence : 157
Classement différent : 144
Âge non calculable : 7004

,contrat_id,souscripteur_id,date_naissance,date_debut,age_debut,age_reference
386,CT0000387,A-22244,1996-09-28,2014-09-01,17.0,30
1355,CT0001356,A-2454,1998-10-17,2016-02-28,17.0,27
2682,CT0002683,S-21318,1999-07-06,2017-03-05,17.0,27
2783,CT0002784,A-30785,2000-07-18,2017-03-27,16.0,26
3210,CT0003211,H-15141,2001-03-23,2017-06-22,16.0,25
4248,CT0004249,S-14454,2001-12-29,2018-01-06,16.0,24
5612,CT0005613,H-30584,2001-02-16,2018-05-14,17.0,25
6253,CT0006254,A-8673,2000-12-29,2018-07-13,17.0,25
9139,CT0009140,A-13520,2002-12-12,2019-04-03,16.0,23
10268,CT0010269,A-24682,2002-12-17,2019-07-19,16.0,23
10618,CT0010619,A-15406,2002-03-08,2019-08-21,17.0,24
12009,CT0012010,A-28903,2003-08-26,2019-12-28,16.0,23
12493,CT0012494,H-29015,2002-10-24,2020-02-07,17.0,23
13103,CT0013104,A-23586,2004-03-19,2020-04-04,16.0,22
13354,CT0013355,A-25985,2002-12-06,2020-04-28,17.0,23
13461,CT0013462,A-4642,2002-05-09,2020-05-08,17.0,24
13594,CT0013595,H-1731,2002-11-07,2020-05-20,17.0,23
14444,CT0014445,A-29762,2004-02-22,2020-08-01,16.0,22
14905,CT0014906,H-5987,2003-07-04,2020-09-10,17.0,23
17855,CT0017856,H-7059,2004-10-08,2021-06-10,16.0,21

## Documenter les résultats de RQ-002

Nous synthétisons les résultats de l’analyse en distinguant les âges calculables, les données manquantes et les changements de classement par rapport au seuil de 18 ans. Nous présentons quelques exemples représentatifs afin de justifier l’importance de calculer l’âge à la date de début du contrat.

Cette synthèse constitue un élément de documentation de RQ-002. Le verdict définitif de conformité doit rester aligné sur la formulation officielle de la règle.

In [9]:
# %% Bloc 6 — Synthèse des résultats de RQ-002

synthese = pd.DataFrame(
    [
        {
            "indicateur": "Nombre total de contrats",
            "valeur": len(contrats),
        },
        {
            "indicateur": "Âge calculable à la souscription",
            "valeur": int(contrats["age_debut"].notna().sum()),
        },
        {
            "indicateur": "Âge non calculable",
            "valeur": int(contrats["age_debut"].isna().sum()),
        },
        {
            "indicateur": "Mineurs à la signature",
            "valeur": int(mineur_signature.sum()),
        },
        {
            "indicateur": "Mineurs à la date de référence",
            "valeur": int(mineur_reference.sum()),
        },
        {
            "indicateur": "Classement différent entre les deux méthodes",
            "valeur": int(changement.sum()),
        },
    ]
)

display(synthese)

# Exemples de contrats dont le classement change
display(
    c.loc[
        changement,
        [
            "contrat_id",
            "souscripteur_id",
            "date_naissance",
            "date_debut",
            "age_debut",
            "age_reference",
        ],
    ].head(10)
)

# Exemples pour lesquels l'âge est impossible à calculer
display(
    contrats.loc[
        contrats["age_debut"].isna(),
        [
            "contrat_id",
            "souscripteur_id",
            "date_debut",
            "date_naissance",
        ],
    ].head(10)
)

                                     indicateur  valeur
0                      Nombre total de contrats  100000
1              Âge calculable à la souscription   92996
2                            Âge non calculable    7004
3                        Mineurs à la signature     301
4                Mineurs à la date de référence     157
5  Classement différent entre les deux méthodes     144

,contrat_id,souscripteur_id,date_naissance,date_debut,age_debut,age_reference
386,CT0000387,A-22244,1996-09-28,2014-09-01,17.0,30
1355,CT0001356,A-2454,1998-10-17,2016-02-28,17.0,27
2682,CT0002683,S-21318,1999-07-06,2017-03-05,17.0,27
2783,CT0002784,A-30785,2000-07-18,2017-03-27,16.0,26
3210,CT0003211,H-15141,2001-03-23,2017-06-22,16.0,25
4248,CT0004249,S-14454,2001-12-29,2018-01-06,16.0,24
5612,CT0005613,H-30584,2001-02-16,2018-05-14,17.0,25
6253,CT0006254,A-8673,2000-12-29,2018-07-13,17.0,25
9139,CT0009140,A-13520,2002-12-12,2019-04-03,16.0,23
10268,CT0010269,A-24682,2002-12-17,2019-07-19,16.0,23

   contrat_id souscripteur_id date_debut date_naissance
5   CT0000006         H-26653 2014-01-02            NaT
14  CT0000015          S-2208 2014-01-04            NaT
21  CT0000022         A-30461 2014-01-11            NaT
30  CT0000031         H-97935 2014-01-23            NaT
31  CT0000032         S-12190 2014-01-23            NaT
41  CT0000042         A-16083 2014-02-02            NaT
45  CT0000046         S-97321 2014-02-03            NaT
52  CT0000053          A-2650 2014-02-09            NaT
58  CT0000059         S-16679 2014-02-11            NaT
68  CT0000069         H-18450 2014-02-17            NaT

## Examiner le schéma des tables de qualité

Nous examinons la structure des tables du schéma `dq` afin d’identifier les champs nécessaires à l’enregistrement des résultats. Cette étape permet de respecter le modèle de données existant et d’éviter les insertions incompatibles avec les contraintes de la base.

In [10]:
# %% Bloc 7 — Examiner le schéma des tables de qualité

tables_dq = [
    "regle",
    "dq_history",
    "rejets",
    "dq_kpi",
    "certificat_qualite",
    "lot_ingestion",
]

for table in tables_dq:
    print(f"\n--- dq.{table} ---")

    schema = query("""
        SELECT
            COLUMN_NAME,
            COLUMN_TYPE,
            IS_NULLABLE,
            COLUMN_KEY,
            COLUMN_DEFAULT
        FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = 'dq'
          AND TABLE_NAME = :table
        ORDER BY ORDINAL_POSITION
    """, WRITER, table=table)

    display(schema)

--- dq.regle ---

,COLUMN_NAME,COLUMN_TYPE,IS_NULLABLE,COLUMN_KEY,COLUMN_DEFAULT
0,rule_id,varchar(10),NO,PRI,None
1,libelle,varchar(255),NO,,None
2,dimension,varchar(40),NO,,None
3,porte,"enum('B','S','G','C')",NO,,None
4,severite,"enum('BLOQUANTE','AVERTISSEMENT')",NO,,None
5,seuil_min,"decimal(5,2)",NO,,100.00

--- dq.dq_history ---

,COLUMN_NAME,COLUMN_TYPE,IS_NULLABLE,COLUMN_KEY,COLUMN_DEFAULT
0,id,bigint(20),NO,PRI,None
1,batch_id,varchar(20),NO,MUL,None
2,couche,"enum('BRONZE','SILVER','GOLD','CRM')",NO,,None
3,rule_id,varchar(10),NO,MUL,None
4,table_cible,varchar(60),NO,,None
5,nb_testees,bigint(20),NO,,None
6,nb_echecs,bigint(20),NO,,None
7,taux_conformite,"decimal(6,3)",YES,,NULL
8,mesure_le,datetime,NO,,current_timestamp()

--- dq.rejets ---

      COLUMN_NAME    COLUMN_TYPE IS_NULLABLE COLUMN_KEY       COLUMN_DEFAULT
0              id     bigint(20)          NO        PRI                 None
1        batch_id    varchar(20)          NO        MUL                 None
2          entite    varchar(40)          NO                            None
3  source_systeme    varchar(20)          NO                           'crm'
4   bronze_row_id     bigint(20)          NO                            None
5         rule_id    varchar(10)          NO                            None
6           porte  enum('S','G')          NO                            None
7           motif   varchar(255)         YES                            NULL
8       rejete_le       datetime          NO             current_timestamp()

--- dq.dq_kpi ---

,COLUMN_NAME,COLUMN_TYPE,IS_NULLABLE,COLUMN_KEY,COLUMN_DEFAULT
0,batch_id,varchar(20),NO,,None
1,couche,"enum('BRONZE','SILVER','GOLD','CRM')",NO,,None
2,taux_moyen,"decimal(6,2)",YES,,NULL
3,total_echecs,"decimal(41,0)",YES,,NULL
4,derniere_mesure,datetime,YES,,current_timestamp()

--- dq.certificat_qualite ---

,COLUMN_NAME,COLUMN_TYPE,IS_NULLABLE,COLUMN_KEY,COLUMN_DEFAULT
0,certificat_id,varchar(30),NO,PRI,None
1,batch_id,varchar(20),NO,,None
2,emis_le,datetime,NO,,current_timestamp()
3,nb_bloquantes_testees,int(11),NO,,None
4,nb_bloquantes_ok,int(11),NO,,None
5,empreinte_gold,char(64),NO,,None
6,decision,"enum('GO','NO_GO')",NO,,None
7,signataire,varchar(80),YES,,NULL
8,commentaire,varchar(500),YES,,NULL

--- dq.lot_ingestion ---

,COLUMN_NAME,COLUMN_TYPE,IS_NULLABLE,COLUMN_KEY,COLUMN_DEFAULT
0,batch_id,varchar(20),NO,PRI,None
1,started_at,datetime,NO,,current_timestamp()
2,finished_at,datetime,YES,,NULL
3,statut,"enum('EN_COURS','TERMINE','ECHEC')",NO,,'EN_COURS'

## Vérifier la définition de RQ-002

Nous consultons le référentiel des règles de qualité pour retrouver la définition officielle de la règle US-13 / RQ-002. Nous vérifions son identifiant, sa description, son seuil éventuel et les modalités de calcul prévues par le projet avant de produire un verdict.

In [11]:
# %% Bloc 8 — Consulter le référentiel des règles

regles = query("""
    SELECT *
    FROM dq.regle
""", WRITER)

display(regles)

,rule_id,libelle,dimension,porte,severite,seuil_min
0,RQ-001,La date de fin d'un contrat est postérieure à ...,Cohérence,S,BLOQUANTE,100.00
1,RQ-002,Un souscripteur personne physique a 18 ans ou ...,Validité métier,G,BLOQUANTE,100.00
2,RQ-003,Le téléphone d'un souscripteur est renseigné (...,Complétude,S,AVERTISSEMENT,98.00
3,RQ-004,"Pour une adresse en France, le téléphone respe...",Validité format,S,AVERTISSEMENT,98.00
4,RQ-005,"Pour une adresse en France, le code postal com...",Validité format,S,AVERTISSEMENT,98.00
5,RQ-006,"Pour une adresse en France, le couple code pos...",Exactitude,S,AVERTISSEMENT,98.00
6,RQ-007,Le pays (code ISO à deux lettres) appartient à...,Intégrité référentielle,S,BLOQUANTE,100.00
7,RQ-008,L'adresse e-mail respecte un motif valide,Validité format,S,AVERTISSEMENT,98.00
8,RQ-009,"Le type de personne vaut prospect, souscripteu...",Validité domaine,S,BLOQUANTE,100.00
9,RQ-010,"La durée de garantie vaut 12, 24, 36 ou 60 mois",Validité domaine,S,BLOQUANTE,100.00
10,RQ-011,Le type de contrat existe dans type_contrat,Intégrité référentielle,G,BLOQUANTE,100.00
11,RQ-012,Le souscripteur d'un contrat existe dans le cl...,Intégrité référentielle,G,BLOQUANTE,100.00
12,RQ-013,L'assuré d'un contrat existe dans le client ; ...,Intégrité référentielle,G,BLOQUANTE,100.00
13,RQ-014,"Adresse de sinistre : format valide, rapproché...","Précision, cohérence",S,BLOQUANTE,100.00
14,RQ-015,Un prospect n'a aucun contrat,Cohérence de statut,G,BLOQUANTE,100.00
15,RQ-016,Un souscripteur a au moins un contrat,Cohérence de statut,G,AVERTISSEMENT,98.00
16,RQ-017,La date de survenance d'un sinistre est compri...,Cohérence inter-tables,G,BLOQUANTE,100.00
17,RQ-018,Client actif : contrat en cours ET cotisation ...,Cohérence de définition,G,BLOQUANTE,100.00
18,RQ-019,Une personne n'a qu'un seul identifiant client...,Unicité,G,BLOQUANTE,100.00
19,RQ-020,Les clés primaires sont uniques et jamais nulles,Unicité,S,BLOQUANTE,100.00
20,RQ-021,Réconciliation source vers bronze : mêmes comp...,"Complétude, intégrité",B,BLOQUANTE,100.00
21,RQ-022,"Chaque ligne bronze porte lot, source, horodat...",Traçabilité,B,BLOQUANTE,100.00
22,RQ-023,Chaque ligne silver et gold référence sa ligne...,Traçabilité,S,BLOQUANTE,100.00
23,RQ-024,Conservation : lignes silver + lignes rejetées...,Complétude,S,BLOQUANTE,100.00
24,RQ-025,Réconciliation gold vers CRM : même comptage e...,Intégrité,C,BLOQUANTE,100.00

## Vérifier l’historique de qualité et le statut du lot

Nous consultons l’historique des mesures de qualité et le statut du lot étudié. Cette vérification permet de savoir si une mesure a déjà été enregistrée et d’éviter de créer des résultats en double ou d’associer le contrôle au mauvais lot.

In [12]:
# %% Bloc 9 — Vérifier l’historique de qualité

historique = query("""
    SELECT *
    FROM dq.dq_history
    WHERE batch_id = :b
    ORDER BY mesure_le DESC
""", WRITER, b=BATCH)

display(historique)

Empty DataFrame
Columns: [id, batch_id, couche, rule_id, table_cible, nb_testees, nb_echecs, taux_conformite, mesure_le]
Index: []

In [13]:
# %% Bloc 10 — Vérifier le statut du lot

lot = query("""
    SELECT *
    FROM dq.lot_ingestion
    WHERE batch_id = :b
""", WRITER, b=BATCH)

display(lot)

Empty DataFrame
Columns: [batch_id, started_at, finished_at, statut]
Index: []

## Lire la définition complète de RQ-002

Nous récupérons la définition complète de la règle RQ-002, son périmètre d’application, sa sévérité et son seuil minimal de conformité. Ces informations permettent de déterminer précisément les conditions de réussite et d’échec avant l’enregistrement officiel de la mesure.

In [14]:
# %% Bloc 11 — Lire la définition complète de RQ-002

regle_rq002 = query("""
    SELECT
        rule_id,
        libelle,
        dimension,
        porte,
        severite,
        seuil_min
    FROM dq.regle
    WHERE rule_id = 'RQ-002'
""", WRITER)

with pd.option_context("display.max_colwidth", None):
    display(regle_rq002)

if len(regle_rq002) != 1:
    raise ValueError("La règle RQ-002 est absente ou présente plusieurs fois.")

print("Définition complète :", regle_rq002.iloc[0]["libelle"])
print("Couche cible :", regle_rq002.iloc[0]["porte"])
print("Sévérité :", regle_rq002.iloc[0]["severite"])
print("Seuil minimal :", regle_rq002.iloc[0]["seuil_min"])

,rule_id,libelle,dimension,porte,severite,seuil_min
0,RQ-002,Un souscripteur personne physique a 18 ans ou plus à la date de début du contrat (un assuré peut être mineur),Validité métier,G,BLOQUANTE,100.00

Définition complète : Un souscripteur personne physique a 18 ans ou plus à la date de début du contrat (un assuré peut être mineur)
Couche cible : G
Sévérité : BLOQUANTE
Seuil minimal : 100.00

## Identifier les tables de la couche Gold

Nous listons les tables et leurs colonnes dans le schéma Gold afin d’identifier la table cible du contrôle RQ-002. Cette étape permet d’appliquer la règle à la couche prévue par le référentiel plutôt qu’aux seules données exploratoires de Bronze.

In [15]:
# %% Bloc 12 — Identifier les tables de la couche Gold

tables_gold = query("""
    SELECT
        TABLE_NAME,
        COLUMN_NAME,
        COLUMN_TYPE
    FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = 'gold'
    ORDER BY TABLE_NAME, ORDINAL_POSITION
""", WRITER)

display(tables_gold)

,TABLE_NAME,COLUMN_NAME,COLUMN_TYPE
0,client_unique,cli_id,char(10)
1,client_unique,nom_reference,varchar(150)
2,client_unique,date_naissance,date
3,client_unique,cp,varchar(10)
4,client_unique,ville,varchar(100)
5,client_unique,pays_iso,char(2)
6,client_unique,telephone,varchar(20)
7,client_unique,email,varchar(150)
8,client_unique,nb_identifiants_source,int(11)
9,client_unique,statut_client,"enum('PROSPECT','ASSURE','ACTIF','INACTIF')"
10,client_unique,_batch_id,varchar(20)
11,xref_identifiants,cli_id,char(10)
12,xref_identifiants,source_systeme,varchar(20)
13,xref_identifiants,source_id,varchar(20)
14,xref_identifiants,bronze_row_id,bigint(20)
15,xref_identifiants,silver_row_id,bigint(20)

## Identifier les tables contenant les contrats

Nous recensons les tables et les colonnes des schémas Silver, Gold et CRM afin d’identifier où sont disponibles les contrats, leurs souscripteurs et les dates de début. Cette vérification permet de déterminer la table cible appropriée pour le contrôle RQ-002 et de respecter son périmètre d’application.

In [16]:
# %% Bloc 13 — Identifier les tables contenant les contrats

tables_metier = query("""
    SELECT
        TABLE_SCHEMA,
        TABLE_NAME,
        COLUMN_NAME,
        COLUMN_TYPE
    FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA IN ('bronze', 'silver', 'gold', 'crm')
      AND (
          COLUMN_NAME IN (
              'contrat_id',
              'souscripteur_id',
              'assure_id',
              'date_debut',
              'date_naissance',
              'type_personne',
              'cli_id',
              '_batch_id'
          )
      )
    ORDER BY TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION
""", WRITER)

display(tables_metier)

,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,COLUMN_TYPE
0,bronze,cif_clients,_batch_id,varchar(20)
1,bronze,cif_compte,_batch_id,varchar(20)
2,bronze,cif_pays,_batch_id,varchar(20)
3,bronze,crm_client,type_personne,varchar(30)
4,bronze,crm_client,date_naissance,varchar(20)
5,bronze,crm_client,_batch_id,varchar(20)
6,bronze,crm_contrat,contrat_id,varchar(255)
7,bronze,crm_contrat,souscripteur_id,varchar(255)
8,bronze,crm_contrat,assure_id,varchar(255)
9,bronze,crm_contrat,date_debut,varchar(255)
10,bronze,crm_contrat,_batch_id,varchar(20)
11,bronze,crm_sinistre,contrat_id,varchar(255)
12,bronze,crm_sinistre,_batch_id,varchar(20)
13,bronze,crm_type_contrat,_batch_id,varchar(20)
14,crm,client,type_personne,varchar(20)
15,crm,client,date_naissance,date
16,crm,contrat,contrat_id,varchar(12)
17,crm,contrat,souscripteur_id,varchar(12)
18,crm,contrat,assure_id,varchar(12)
19,crm,contrat,date_debut,date
20,crm,sinistre,contrat_id,varchar(12)
21,gold,client_unique,cli_id,char(10)
22,gold,client_unique,date_naissance,date
23,gold,client_unique,_batch_id,varchar(20)
24,gold,xref_identifiants,cli_id,char(10)
25,silver,client,type_personne,"enum('prospect','souscripteur','assure')"
26,silver,client,date_naissance,date
27,silver,client,_batch_id,varchar(20)

## Vérifier le type de personne et les identifiants

Nous examinons les valeurs du type de personne dans les données CRM, Bronze et Silver, puis nous vérifions la correspondance entre les identifiants des souscripteurs et les clients disponibles. Cette étape permet de distinguer les personnes physiques des autres types de clients et de préparer une évaluation fiable de RQ-002.

In [17]:
# %% Bloc 14 — Vérifier le type de personne et les identifiants

print("1. Types de personne dans CRM")
display(query("""
    SELECT
        type_personne,
        COUNT(*) AS nombre
    FROM crm.client
    GROUP BY type_personne
    ORDER BY type_personne
""", WRITER))

print("2. Types de personne dans Bronze pour le lot")
display(query("""
    SELECT
        type_personne,
        COUNT(*) AS nombre
    FROM bronze.crm_client
    WHERE _batch_id = :b
    GROUP BY type_personne
    ORDER BY type_personne
""", WRITER, b=BATCH))

print("3. Types de personne dans Silver pour le lot")
display(query("""
    SELECT
        type_personne,
        COUNT(*) AS nombre
    FROM silver.client
    WHERE _batch_id = :b
    GROUP BY type_personne
    ORDER BY type_personne
""", WRITER, b=BATCH))

1. Types de personne dans CRM

  type_personne  nombre
0  SOUSCRIPTEUR      30
1  Souscripteur      50
2        assure   28944
3        assuré      40
4        client      60
5        prosp.      20
6      prospect   20958
7  souscripteur   49898

2. Types de personne dans Bronze pour le lot

  type_personne  nombre
0  SOUSCRIPTEUR      30
1  Souscripteur      50
2        assure   28944
3        assuré      40
4        client      60
5        prosp.      20
6      prospect   20958
7  souscripteur   49898

3. Types de personne dans Silver pour le lot

Empty DataFrame
Columns: [type_personne, nombre]
Index: []

## Diagnostiquer les cas de RQ-002

Nous rapprochons les contrats Bronze des données clients afin d’identifier les souscripteurs personnes physiques âgés de moins de 18 ans à la date de début du contrat. Nous isolons également les cas dont les dates ou les informations du souscripteur sont insuffisantes pour conclure. Ce diagnostic permet de préparer le contrôle sans enregistrer prématurément un verdict officiel.

In [18]:
# %% Bloc 15 — Diagnostiquer les cas RQ-002 dans Bronze

diagnostic_rq002 = query("""
    SELECT
        c.contrat_id,
        c.souscripteur_id,
        c.date_debut,
        cl.type_personne,
        cl.date_naissance,
        CASE
            WHEN c.date_debut IS NULL
              OR TRIM(c.date_debut) = ''
              OR cl.date_naissance IS NULL
              OR TRIM(cl.date_naissance) = ''
              OR STR_TO_DATE(c.date_debut, '%Y-%m-%d') IS NULL
              OR STR_TO_DATE(cl.date_naissance, '%Y-%m-%d') IS NULL
            THEN NULL
            ELSE TIMESTAMPDIFF(
                YEAR,
                STR_TO_DATE(cl.date_naissance, '%Y-%m-%d'),
                STR_TO_DATE(c.date_debut, '%Y-%m-%d')
            )
        END AS age_a_la_souscription
    FROM bronze.crm_contrat AS c
    LEFT JOIN bronze.crm_client AS cl
        ON c.souscripteur_id = cl.client_id
       AND cl._batch_id = c._batch_id
    WHERE c._batch_id = :b
""", WRITER, b=BATCH)

# Normaliser les libellés pour analyser les types de personne.
diagnostic_rq002["type_personne_normalise"] = (
    diagnostic_rq002["type_personne"]
    .astype("string")
    .str.strip()
    .str.lower()
)

display(
    diagnostic_rq002[
        "type_personne_normalise"
    ].value_counts(dropna=False).rename_axis(
        "type_personne"
    ).reset_index(name="nombre")
)

# Les libellés exacts sont à confirmer avec le résultat du bloc 14.
physique = diagnostic_rq002[
    diagnostic_rq002["type_personne_normalise"].isin(
        ["souscripteur", "personne physique", "physique"]
    )
].copy()

mineurs = physique[
    physique["age_a_la_souscription"].notna()
    & (physique["age_a_la_souscription"] < 18)
]

non_evaluables = diagnostic_rq002[
    diagnostic_rq002["age_a_la_souscription"].isna()
]

print(f"Contrats du lot : {len(diagnostic_rq002)}")
print(f"Souscripteurs personnes physiques identifiés : {len(physique)}")
print(f"Cas de moins de 18 ans : {len(mineurs)}")
print(f"Cas non évaluables : {len(non_evaluables)}")

display(mineurs.head(20))
display(non_evaluables.head(20))

  type_personne  nombre
0  souscripteur   97870
1      prospect    1022
2          <NA>    1000
3        client      53
4        assuré      38
5        prosp.      17

Contrats du lot : 100000
Souscripteurs personnes physiques identifiés : 97870
Cas de moins de 18 ans : 301
Cas non évaluables : 7004

,contrat_id,souscripteur_id,date_debut,type_personne,date_naissance,age_a_la_souscription,type_personne_normalise
386,CT0000387,A-22244,2014-09-01,souscripteur,1996-09-28,17.0,souscripteur
1355,CT0001356,A-2454,2016-02-28,souscripteur,1998-10-17,17.0,souscripteur
2682,CT0002683,S-21318,2017-03-05,souscripteur,1999-07-06,17.0,souscripteur
2783,CT0002784,A-30785,2017-03-27,souscripteur,2000-07-18,16.0,souscripteur
3210,CT0003211,H-15141,2017-06-22,souscripteur,2001-03-23,16.0,souscripteur
4248,CT0004249,S-14454,2018-01-06,souscripteur,2001-12-29,16.0,souscripteur
5612,CT0005613,H-30584,2018-05-14,souscripteur,2001-02-16,17.0,souscripteur
6253,CT0006254,A-8673,2018-07-13,souscripteur,2000-12-29,17.0,souscripteur
9139,CT0009140,A-13520,2019-04-03,souscripteur,2002-12-12,16.0,souscripteur
10268,CT0010269,A-24682,2019-07-19,souscripteur,2002-12-17,16.0,souscripteur
10618,CT0010619,A-15406,2019-08-21,souscripteur,2002-03-08,17.0,souscripteur
12009,CT0012010,A-28903,2019-12-28,souscripteur,2003-08-26,16.0,souscripteur
12493,CT0012494,H-29015,2020-02-07,souscripteur,2002-10-24,17.0,souscripteur
13103,CT0013104,A-23586,2020-04-04,souscripteur,2004-03-19,16.0,souscripteur
13354,CT0013355,A-25985,2020-04-28,souscripteur,2002-12-06,17.0,souscripteur
13461,CT0013462,A-4642,2020-05-08,souscripteur,2002-05-09,17.0,souscripteur
13594,CT0013595,H-1731,2020-05-20,souscripteur,2002-11-07,17.0,souscripteur
14444,CT0014445,A-29762,2020-08-01,souscripteur,2004-02-22,16.0,souscripteur
14905,CT0014906,H-5987,2020-09-10,souscripteur,2003-07-04,17.0,souscripteur
17855,CT0017856,H-7059,2021-06-10,souscripteur,2004-10-08,16.0,souscripteur

,contrat_id,souscripteur_id,date_debut,type_personne,date_naissance,age_a_la_souscription,type_personne_normalise
5,CT0000006,H-26653,2014-01-02,souscripteur,None,NaN,souscripteur
14,CT0000015,S-2208,2014-01-04,souscripteur,None,NaN,souscripteur
21,CT0000022,A-30461,2014-01-11,souscripteur,None,NaN,souscripteur
30,CT0000031,H-97935,2014-01-23,None,None,NaN,<NA>
31,CT0000032,S-12190,2014-01-23,souscripteur,None,NaN,souscripteur
41,CT0000042,A-16083,2014-02-02,souscripteur,None,NaN,souscripteur
45,CT0000046,S-97321,2014-02-03,None,None,NaN,<NA>
52,CT0000053,A-2650,2014-02-09,souscripteur,None,NaN,souscripteur
58,CT0000059,S-16679,2014-02-11,souscripteur,None,NaN,souscripteur
68,CT0000069,H-18450,2014-02-17,souscripteur,None,NaN,souscripteur
70,CT0000071,S-95441,2014-02-17,None,None,NaN,<NA>
71,CT0000072,S-97658,2014-02-17,None,None,NaN,<NA>
76,CT0000077,H-6739,2014-02-19,souscripteur,None,NaN,souscripteur
97,CT0000098,H-4702,2014-03-06,souscripteur,None,NaN,souscripteur
117,CT0000118,A-10381,2014-03-19,souscripteur,None,NaN,souscripteur
150,CT0000151,A-10166,2014-04-10,souscripteur,None,NaN,souscripteur
154,CT0000155,A-19992,2014-04-14,souscripteur,None,NaN,souscripteur
175,CT0000176,H-5188,2014-04-24,souscripteur,None,NaN,souscripteur
187,CT0000188,A-95721,2014-05-03,None,None,NaN,<NA>
190,CT0000191,H-33449,2014-05-04,souscripteur,None,NaN,souscripteur

## Identifier les causes de non-évaluation de RQ-002

In [19]:

# Paso 16 — Identifier les causes de non-évaluation de RQ-002

diag = diagnostic_rq002.copy()

# Convertir les dates en dates exploitables
diag["date_debut_parsee"] = pd.to_datetime(
    diag["date_debut"], errors="coerce"
)
diag["date_naissance_parsee"] = pd.to_datetime(
    diag["date_naissance"], errors="coerce"
)

# Identifier les causes possibles
diag["cause_non_evaluable"] = "Age calculable"

diag.loc[
    diag["type_personne_normalise"].isna(),
    "cause_non_evaluable"
] = "Type de personne manquant"

diag.loc[
    diag["date_debut_parsee"].isna(),
    "cause_non_evaluable"
] = "Date de début manquante ou invalide"

diag.loc[
    diag["date_naissance_parsee"].isna()
    & diag["date_debut_parsee"].notna(),
    "cause_non_evaluable"
] = "Date de naissance manquante ou invalide"

# Répartition globale
print("Répartition des causes")
display(
    diag["cause_non_evaluable"]
    .value_counts(dropna=False)
    .rename_axis("cause")
    .reset_index(name="nombre")
)

# Répartition parmi les souscripteurs identifiés
souscripteurs = diag[
    diag["type_personne_normalise"].eq("souscripteur")
].copy()

print("Répartition parmi les souscripteurs identifiés")
display(
    souscripteurs["cause_non_evaluable"]
    .value_counts(dropna=False)
    .rename_axis("cause")
    .reset_index(name="nombre")
)

print("Souscripteurs avec âge calculable :", 
      souscripteurs["age_a_la_souscription"].notna().sum())

print("Souscripteurs de moins de 18 ans :",
      (
          souscripteurs["age_a_la_souscription"].notna()
          & (souscripteurs["age_a_la_souscription"] < 18)
      ).sum())

Répartition des causes

                                     cause  nombre
0                           Age calculable   92996
1  Date de naissance manquante ou invalide    7004

Répartition parmi les souscripteurs identifiés

                                     cause  nombre
0                           Age calculable   91875
1  Date de naissance manquante ou invalide    5995

Souscripteurs avec âge calculable : 91875
Souscripteurs de moins de 18 ans : 301

### US-13 — Contrôle de la règle RQ-002 : âge du souscripteur

**Objectif :** mesurer les écarts à la règle RQ-002, selon laquelle un souscripteur personne physique doit avoir au moins 18 ans à la date de début du contrat. Un assuré peut être mineur.

L'analyse compare deux calculs :
- **Âge à la souscription :** âge atteint à la date de début du contrat. C'est le calcul pertinent pour évaluer la conformité à RQ-002.
- **Âge à la date de référence :** âge atteint au 1er octobre 2026. Ce calcul permet d'illustrer les divergences de classification entre l'âge historique et l'âge actuel de référence.

Les résultats présentés sont des indicateurs exploratoires calculés sur les données Bronze du lot. Les contrats dont la date de naissance ou la date de début est manquante ou invalide sont classés comme non évaluables et ne sont pas considérés comme conformes par défaut.

Un cas réel divergent est présenté avec son identifiant de contrat, sa date de naissance, sa date de début, les deux âges calculés et le résultat du contrôle historique.

In [21]:

# US-13 — RQ-002 : comparaison des âges et cas divergent

import pandas as pd

# Date de référence utilisée pour calculer l'âge actuel
DATE_REFERENCE = pd.Timestamp("2026-10-01")

# Repartir du diagnostic déjà calculé à l'étape 15
us13 = diagnostic_rq002.copy()

# Convertir les dates
us13["date_debut"] = pd.to_datetime(
    us13["date_debut"], errors="coerce"
)
us13["date_naissance"] = pd.to_datetime(
    us13["date_naissance"], errors="coerce"
)

# Calculer l'âge atteint à une date donnée
def age_at_date(date_naissance, date_reference):
    age = date_reference.dt.year - date_naissance.dt.year
    anniversaire_non_atteint = (
        (date_reference.dt.month < date_naissance.dt.month)
        | (
            (date_reference.dt.month == date_naissance.dt.month)
            & (date_reference.dt.day < date_naissance.dt.day)
        )
    )
    return (age - anniversaire_non_atteint.astype("Int64")).astype("Int64")

# Âge à la date de début du contrat
us13["age_debut"] = age_at_date(
    us13["date_naissance"], us13["date_debut"]
)

# Âge à la date de référence, pour les mêmes personnes
date_ref_serie = pd.Series(
    DATE_REFERENCE, index=us13.index
)
us13["age_reference"] = age_at_date(
    us13["date_naissance"], date_ref_serie
)

# Restriction aux souscripteurs identifiés
souscripteur = us13[
    us13["type_personne_normalise"].eq("souscripteur")
].copy()

# Cas évaluables : dates exploitables pour les deux calculs
evaluables = souscripteur[
    souscripteur["age_debut"].notna()
    & souscripteur["age_reference"].notna()
].copy()

# Indicateurs
nb_contrats = len(us13)
nb_souscripteurs = len(souscripteur)
nb_evaluables = len(evaluables)
nb_non_evaluables = nb_souscripteurs - nb_evaluables

# Le contrôle RQ-002 porte sur l'âge au début du contrat
echecs_debut = evaluables[evaluables["age_debut"] < 18]

# Comparaison à la date de référence
mineurs_reference = evaluables[
    evaluables["age_reference"] < 18
]

# Cas où la classification mineur/majeur change
divergents = evaluables[
    (evaluables["age_debut"] < 18)
    != (evaluables["age_reference"] < 18)
].copy()

# Tableau de synthèse
synthese_us13 = pd.DataFrame([
    ["Contrats analysés", nb_contrats],
    ["Souscripteurs identifiés", nb_souscripteurs],
    ["Souscripteurs évaluables", nb_evaluables],
    ["Souscripteurs non évaluables", nb_non_evaluables],
    ["Échecs RQ-002 : moins de 18 ans au début", len(echecs_debut)],
    ["Moins de 18 ans à la date de référence", len(mineurs_reference)],
    ["Changements de classification", len(divergents)],
], columns=["Indicateur", "Nombre"])

print("Synthèse US-13 — RQ-002")
display(synthese_us13)

# Sélectionner un cas divergent réel
if not divergents.empty:
    cas = divergents.sort_values(
        ["date_debut", "contrat_id"]
    ).iloc[0]

    print("Cas réel divergent")
    display(pd.DataFrame([{
        "contrat_id": cas["contrat_id"],
        "souscripteur_id": cas["souscripteur_id"],
        "date_naissance": cas["date_naissance"].date(),
        "date_debut_contrat": cas["date_debut"].date(),
        "date_reference": DATE_REFERENCE.date(),
        "age_au_debut": int(cas["age_debut"]),
        "age_a_la_reference": int(cas["age_reference"]),
        "resultat_RQ002": (
            "ÉCHEC"
            if cas["age_debut"] < 18
            else "CONFORME"
        ),
        "classification_divergente": True
    }]))
else:
    print("Aucun cas divergent trouvé parmi les contrats évaluables.")

Synthèse US-13 — RQ-002

                                 Indicateur  Nombre
0                         Contrats analysés  100000
1                  Souscripteurs identifiés   97870
2                  Souscripteurs évaluables   91875
3              Souscripteurs non évaluables    5995
4  Échecs RQ-002 : moins de 18 ans au début     301
5    Moins de 18 ans à la date de référence     157
6             Changements de classification     144

Cas réel divergent

,contrat_id,souscripteur_id,date_naissance,date_debut_contrat,date_reference,age_au_debut,age_a_la_reference,resultat_RQ002,classification_divergente
0,CT0000387,A-22244,1996-09-28,2014-09-01,2026-10-01,17,30,ÉCHEC,True

In [26]:

from pathlib import Path
import shutil

origen = Path("/home/jovyan/work/notebooks/S2_g02.ipynb")
copia = Path("/home/jovyan/work/notebooks/S2_g02_backup.ipynb")

shutil.copy2(origen, copia)

print("Copia de seguridad creada:", copia.exists())
print("Tamaño:", copia.stat().st_size, "bytes")

Copia de seguridad creada: True
Tamaño: 167010 bytes