Chargement & récupération

In [1]:
from pathlib import Path
import pandas as pd
from sqlalchemy import create_engine, text
from IPython.display import display

# connexion à MariaDB
READER = create_engine('mysql+pymysql://reader:reader@mariadb:3306')
BATCH = 'L-2026-10-01'  

def query(sql, **params):
    with READER.connect() as cx:
        return pd.read_sql(text(sql), cx, params=params, coerce_float=False)
    
display(query("select * from bronze.crm_client limit 5"))

,bronze_row_id,client_id,type_personne,nom,prenom,raison_sociale,date_naissance,adresse,cp,ville,pays,telephone,email,date_creation,_batch_id,_source_system,_ingested_at,_row_hash
0,100001,A-1000,souscripteur,Thomas,Sandrine,None,1975-04-16,31 rue Anatole France,69300,Caluire-et-Cuire,FR,0346234195,sandrine.thomas1093@free.fr,2019-12-25,L-2026-10-01,crm,2026-10-21 13:20:04,106f47a3d40639d6
1,100002,A-10000,assure,Leroy,Karim,None,1942-03-02,81 rue du Moulin,73000,Chambéry,FR,0212942708,contact@batimentgiraudsa6308.fr,2018-06-30,L-2026-10-01,crm,2026-10-21 13:20:04,219ae81290d150ee
2,100003,A-10001,prospect,Dumas,Zoé,None,1980-11-02,16 rue de Provence,71000,Mâcon,,None,None,2018-04-25,L-2026-10-01,crm,2026-10-21 13:20:04,f708f53e876668f1
3,100004,A-10002,souscripteur,Denis,Emma,None,2009-07-23,45 avenue du Général de Gaulle,69009,Saint-Étienne,FR,0129310237,None,2023-03-24,L-2026-10-01,crm,2026-10-21 13:20:04,65ca3c0f173f80ef
4,100005,A-10003,prospect,Perrin,Catherine,None,1957-09-02,88 rue des Jardins,69100,Villeurbanne,FR,+33582679882,romain.durand3630@free.fr,2022-06-15,L-2026-10-01,crm,2026-10-21 13:20:04,d154a03a95a5aafd

In [2]:
# vérif de l'existance des tables bronze 

TABLES_BRONZE = [
    'crm_client', 'crm_contrat', 'crm_sinistre', 'crm_type_contrat',
    'cif_clients', 'cif_compte', 'cif_pays'
]

tables_existantes = query("""
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'bronze'
    ORDER BY table_name
""")
display(tables_existantes)

lots = query("""
    SELECT _batch_id, COUNT(*) AS nb_lignes
    FROM bronze.crm_client
    GROUP BY _batch_id
    ORDER BY _batch_id
""")
display(lots)

assert set(TABLES_BRONZE).issubset(set(tables_existantes['table_name'])), \
    'Table manquante ou plusieurs'
assert BATCH in set(lots['_batch_id']), \
    f'Le lot {BATCH} = absent '


#recup noms de colonnes & si ya des null
display(query("""select table_name, column_name, column_type, is_nullable  from information_schema.columns where table_schema = 'bronze'
and table_name in ('crm_client', 'crm_contrat', 'crm_type_contrat') order by table_name, ordinal_position"""))

         table_name
0       cif_clients
1        cif_compte
2          cif_pays
3        crm_client
4       crm_contrat
5      crm_sinistre
6  crm_type_contrat

      _batch_id  nb_lignes
0  L-2026-10-01     100000

          table_name               column_name   column_type is_nullable
0         crm_client             bronze_row_id    bigint(20)          NO
1         crm_client                 client_id   varchar(12)         YES
2         crm_client             type_personne   varchar(30)         YES
3         crm_client                       nom  varchar(150)         YES
4         crm_client                    prenom   varchar(80)         YES
5         crm_client            raison_sociale  varchar(150)         YES
6         crm_client            date_naissance   varchar(20)         YES
7         crm_client                   adresse  varchar(255)         YES
8         crm_client                        cp   varchar(10)         YES
9         crm_client                     ville  varchar(100)         YES
10        crm_client                      pays   varchar(40)         YES
11        crm_client                 telephone   varchar(30)         YES
12        crm_client                     email  varchar(150)         YES
13        crm_client             date_creation   varchar(20)         YES
14        crm_client                 _batch_id   varchar(20)          NO
15        crm_client            _source_system   varchar(20)          NO
16        crm_client              _ingested_at      datetime          NO
17        crm_client                 _row_hash      char(16)          NO
18       crm_contrat             bronze_row_id    bigint(20)          NO
19       crm_contrat                contrat_id  varchar(255)         YES
20       crm_contrat           souscripteur_id  varchar(255)         YES
21       crm_contrat                 assure_id  varchar(255)         YES
22       crm_contrat                 code_type  varchar(255)         YES
23       crm_contrat                date_debut  varchar(255)         YES
24       crm_contrat                  date_fin  varchar(255)         YES
25       crm_contrat       duree_garantie_mois  varchar(255)         YES
26       crm_contrat            prime_annuelle  varchar(255)         YES
27       crm_contrat  date_derniere_cotisation  varchar(255)         YES
28       crm_contrat                 _batch_id   varchar(20)          NO
29       crm_contrat            _source_system   varchar(20)          NO
30       crm_contrat              _ingested_at      datetime          NO
31       crm_contrat                 _row_hash      char(16)          NO
32  crm_type_contrat             bronze_row_id    bigint(20)          NO
33  crm_type_contrat                 code_type  varchar(255)         YES
34  crm_type_contrat                   libelle  varchar(255)         YES
35  crm_type_contrat                   branche  varchar(255)         YES
36  crm_type_contrat                 _batch_id   varchar(20)          NO
37  crm_type_contrat            _source_system   varchar(20)          NO
38  crm_type_contrat              _ingested_at      datetime          NO
39  crm_type_contrat                 _row_hash      char(16)          NO

In [3]:
def afficher_colonnes(table):
    return query("""
        SELECT column_name, column_type, is_nullable
        FROM information_schema.columns
        WHERE table_schema = 'bronze' AND table_name = :table
        ORDER BY ordinal_position
    """, table=table)

for table in ['crm_client', 'crm_contrat', 'crm_type_contrat']:
    print(f'--- bronze.{table} ---')
    display(afficher_colonnes(table))

--- bronze.crm_client ---

       column_name   column_type is_nullable
0    bronze_row_id    bigint(20)          NO
1        client_id   varchar(12)         YES
2    type_personne   varchar(30)         YES
3              nom  varchar(150)         YES
4           prenom   varchar(80)         YES
5   raison_sociale  varchar(150)         YES
6   date_naissance   varchar(20)         YES
7          adresse  varchar(255)         YES
8               cp   varchar(10)         YES
9            ville  varchar(100)         YES
10            pays   varchar(40)         YES
11       telephone   varchar(30)         YES
12           email  varchar(150)         YES
13   date_creation   varchar(20)         YES
14       _batch_id   varchar(20)          NO
15  _source_system   varchar(20)          NO
16    _ingested_at      datetime          NO
17       _row_hash      char(16)          NO

--- bronze.crm_contrat ---

                 column_name   column_type is_nullable
0              bronze_row_id    bigint(20)          NO
1                 contrat_id  varchar(255)         YES
2            souscripteur_id  varchar(255)         YES
3                  assure_id  varchar(255)         YES
4                  code_type  varchar(255)         YES
5                 date_debut  varchar(255)         YES
6                   date_fin  varchar(255)         YES
7        duree_garantie_mois  varchar(255)         YES
8             prime_annuelle  varchar(255)         YES
9   date_derniere_cotisation  varchar(255)         YES
10                 _batch_id   varchar(20)          NO
11            _source_system   varchar(20)          NO
12              _ingested_at      datetime          NO
13                 _row_hash      char(16)          NO

--- bronze.crm_type_contrat ---

      column_name   column_type is_nullable
0   bronze_row_id    bigint(20)          NO
1       code_type  varchar(255)         YES
2         libelle  varchar(255)         YES
3         branche  varchar(255)         YES
4       _batch_id   varchar(20)          NO
5  _source_system   varchar(20)          NO
6    _ingested_at      datetime          NO
7       _row_hash      char(16)          NO

In [4]:
#chargment des tables
clients = query("select * from bronze.crm_client where _batch_id = :batch", batch=BATCH)
contrats = query("select * from bronze.crm_contrat where _batch_id = :batch", batch=BATCH)
type_contrats = query("select * from bronze.crm_type_contrat where _batch_id = :batch", batch=BATCH)


print("Clients :", len(clients))
print("Contrats :", len(contrats))
print("Type Contrats :", len(type_contrats))

display(clients.head())
display(contrats.head())
display(type_contrats.head())

Clients : 100000
Contrats : 100000
Type Contrats : 12

,bronze_row_id,client_id,type_personne,nom,prenom,raison_sociale,date_naissance,adresse,cp,ville,pays,telephone,email,date_creation,_batch_id,_source_system,_ingested_at,_row_hash
0,100001,A-1000,souscripteur,Thomas,Sandrine,None,1975-04-16,31 rue Anatole France,69300,Caluire-et-Cuire,FR,0346234195,sandrine.thomas1093@free.fr,2019-12-25,L-2026-10-01,crm,2026-10-21 13:20:04,106f47a3d40639d6
1,100002,A-10000,assure,Leroy,Karim,None,1942-03-02,81 rue du Moulin,73000,Chambéry,FR,0212942708,contact@batimentgiraudsa6308.fr,2018-06-30,L-2026-10-01,crm,2026-10-21 13:20:04,219ae81290d150ee
2,100003,A-10001,prospect,Dumas,Zoé,None,1980-11-02,16 rue de Provence,71000,Mâcon,,None,None,2018-04-25,L-2026-10-01,crm,2026-10-21 13:20:04,f708f53e876668f1
3,100004,A-10002,souscripteur,Denis,Emma,None,2009-07-23,45 avenue du Général de Gaulle,69009,Saint-Étienne,FR,0129310237,None,2023-03-24,L-2026-10-01,crm,2026-10-21 13:20:04,65ca3c0f173f80ef
4,100005,A-10003,prospect,Perrin,Catherine,None,1957-09-02,88 rue des Jardins,69100,Villeurbanne,FR,+33582679882,romain.durand3630@free.fr,2022-06-15,L-2026-10-01,crm,2026-10-21 13:20:04,d154a03a95a5aafd

,bronze_row_id,contrat_id,souscripteur_id,assure_id,code_type,date_debut,date_fin,duree_garantie_mois,prime_annuelle,date_derniere_cotisation,_batch_id,_source_system,_ingested_at,_row_hash
0,100001,CT0000001,A-18356,0,T02,2009-08-10,2019-08-09,120,615.15,2019-07-15,L-2026-10-01,crm,2026-10-21 13:20:19,12aa30fae234a6fd
1,100002,CT0000002,H-22766,H-28231,T07,2009-08-22,2019-08-21,120,237.93,2019-08-10,L-2026-10-01,crm,2026-10-21 13:20:19,c850ae6eae5a2a0f
2,100003,CT0000003,H-35362,H-26949,T05,2011-04-05,2021-04-04,120,411.58,2021-02-14,L-2026-10-01,crm,2026-10-21 13:20:19,60038bf9f8445d72
3,100004,CT0000004,A-28218,A-34217,T03,2012-09-23,2022-09-22,120,468.93,2022-09-18,L-2026-10-01,crm,2026-10-21 13:20:19,b990ae106c92c9ed
4,100005,CT0000005,A-34113,A-30971,T04,2014-01-02,2019-01-01,60,970.62,2018-11-28,L-2026-10-01,crm,2026-10-21 13:20:19,8f0af149032681e1

,bronze_row_id,code_type,libelle,branche,_batch_id,_source_system,_ingested_at,_row_hash
0,13,T01,Auto tous risques,AUTO,L-2026-10-01,crm,2026-10-21 13:20:40,a89d3b80ca3aadde
1,14,T02,Auto au tiers,AUTO,L-2026-10-01,crm,2026-10-21 13:20:40,26270a12ef015ca5
2,15,T03,Moto et scooter,AUTO,L-2026-10-01,crm,2026-10-21 13:20:40,861e16a5d317e92f
3,16,T04,Auto jeune conducteur,AUTO,L-2026-10-01,crm,2026-10-21 13:20:40,45b35b31f12331fb
4,17,T05,Multirisque habitation propriétaire,HABITATION,L-2026-10-01,crm,2026-10-21 13:20:40,4db6aa44a8bcf9cd

In [5]:
# Vérification des règles

In [6]:
# preparation controle
import great_expectations as ge

resultats = []

def controler(regle, description, donnees, condition, seuil=1.0):
    condition = pd.Series(condition, index=donnees.index).fillna(False).astype(bool)
    test = ge.from_pandas(pd.DataFrame({"conforme": condition}))
    resultat = test.expect_column_values_to_be_in_set(
        "conforme", [True], mostly=seuil
    )

    nb = len(condition)
    erreurs = int((~condition).sum())
    taux = round(100 * (nb - erreurs) / nb, 2) if nb else 0

    print(f"{regle} - {description}")
    print(f"Lignes contrôlées : {nb}")
    print(f"Anomalies : {erreurs}")
    print(f"Conformité : {taux}%")
    print(f"Seuil respecté : {resultat['success']}")

    resultats.append({
        "regle": regle,
        "description": description,
        "lignes": nb,
        "anomalies": erreurs,
        "conformite_pct": taux,
        "seuil_respecte": resultat["success"],
    })
    return donnees.loc[~condition]

In [7]:
#RQ-001 : date de fin après date de début
debut = pd.to_datetime(contrats["date_debut"], errors="coerce")
fin = pd.to_datetime(contrats["date_fin"], errors="coerce")

ok = debut.notna() & fin.notna() & (fin > debut)

anomalies_RQ001 = controler(
    "RQ-001", "Date de fin après date de début", contrats, ok
)

display(anomalies_RQ001)

RQ-001 - Date de fin après date de début
Lignes contrôlées : 100000
Anomalies : 800
Conformité : 99.2%
Seuil respecté : False

,bronze_row_id,contrat_id,souscripteur_id,assure_id,code_type,date_debut,date_fin,duree_garantie_mois,prime_annuelle,date_derniere_cotisation,_batch_id,_source_system,_ingested_at,_row_hash
43,100044,CT0000044,H-26157,S-24675,T07,2014-02-03,2014-02-03,60,264.74,2019-01-16,L-2026-10-01,crm,2026-10-21 13:20:19,bdc874af3afa3584
105,100106,CT0000106,H-27702,0,T08,2014-03-11,2014-03-11,60,948.52,2019-02-08,L-2026-10-01,crm,2026-10-21 13:20:19,f69d486afa798997
146,100147,CT0000147,H-29684,A-32625,T05,2014-04-05,2014-03-08,60,408.28,2019-03-12,L-2026-10-01,crm,2026-10-21 13:20:19,089c78feeb76ba8a
157,100158,CT0000158,A-17235,A-2559,T03,2014-04-16,2014-04-16,60,414.72,2019-04-05,L-2026-10-01,crm,2026-10-21 13:20:19,0866a6e48593530e
209,100210,CT0000210,H-26425,S-23715,T07,2014-05-19,2014-05-19,60,250.54,2019-04-28,L-2026-10-01,crm,2026-10-21 13:20:19,a0a0761a87d4b7ba
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49818,149819,CT0049819,A-25841,0,T04,2025-08-26,2025-08-26,12,1285.55,2026-08-15,L-2026-10-01,crm,2026-10-21 13:20:23,ead7b95054d08687
50121,150122,CT0050122,S-24091,0,T12,2025-09-02,2025-08-08,12,222.15,2026-07-15,L-2026-10-01,crm,2026-10-21 13:20:23,1869dd955de212e8
50635,150636,CT0050636,H-3963,A-39874,T05,2025-09-17,2025-09-17,12,318.86,2026-08-09,L-2026-10-01,crm,2026-10-21 13:20:23,7cbbe1ae9695c20c
50990,150991,CT0050991,H-17089,0,T07,2025-09-27,2025-09-24,12,289.68,2026-07-30,L-2026-10-01,crm,2026-10-21 13:20:23,29cdf97969d9fca5
51082,151083,CT0051083,S-24506,0,T10,2025-09-29,2025-09-01,12,2768.72,2026-09-24,L-2026-10-01,crm,2026-10-21 13:20:23,db524b7fbe29cdf6

In [8]:
#RQ-002 : souscripteur majeur à la date du contrat
test = contrats.merge(
    clients[["client_id", "type_personne", "date_naissance"]],
    left_on="souscripteur_id",
    right_on="client_id",
    how="left"
)

debut = pd.to_datetime(test["date_debut"], errors="coerce")
naissance = pd.to_datetime(test["date_naissance"], errors="coerce")

age = debut.dt.year - naissance.dt.year
age -= (
    (debut.dt.month < naissance.dt.month)
    | ((debut.dt.month == naissance.dt.month) & (debut.dt.day < naissance.dt.day))
).astype("float")

ok = (
    test["type_personne"].astype("string").str.strip().str.lower().eq("souscripteur")
    & naissance.notna()
    & debut.notna()
    & (age >= 18)
)

anomalies_RQ002 = controler(
    "RQ-002", "Souscripteur majeur au début du contrat", test, ok
)

display(anomalies_RQ002)

RQ-002 - Souscripteur majeur au début du contrat
Lignes contrôlées : 100000
Anomalies : 8426
Conformité : 91.57%
Seuil respecté : False

,bronze_row_id,contrat_id,souscripteur_id,assure_id,code_type,date_debut,date_fin,duree_garantie_mois,prime_annuelle,date_derniere_cotisation,_batch_id,_source_system,_ingested_at,_row_hash,client_id,type_personne,date_naissance
5,100006,CT0000006,H-26653,0,T05,2014-01-02,2019-01-01,60,405.07,2018-12-07,L-2026-10-01,crm,2026-10-21 13:20:19,221200c3998088db,H-26653,souscripteur,None
14,100015,CT0000015,S-2208,H-6365,T10,2014-01-04,2019-01-03,60,2016.27,2018-12-29,L-2026-10-01,crm,2026-10-21 13:20:19,17fb6d5c9eaf2713,S-2208,souscripteur,None
21,100022,CT0000022,A-30461,0,T02,2014-01-11,2019-01-10,60,676.09,2018-11-20,L-2026-10-01,crm,2026-10-21 13:20:19,5574a960deed8de5,A-30461,souscripteur,None
30,100031,CT0000031,H-97935,A-26914,T08,2014-01-23,2019-01-22,60,830.17,2018-11-29,L-2026-10-01,crm,2026-10-21 13:20:19,eae3a9fe872ef71f,NaN,NaN,NaN
31,100032,CT0000032,S-12190,S-25364,T09,2014-01-23,2019-01-22,60,740.13,2019-01-19,L-2026-10-01,crm,2026-10-21 13:20:19,59adaed9e0bf1fb4,S-12190,souscripteur,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99948,199949,CT0099949,H-26534,S-4801,T07,2026-10-01,2027-09-30,12,335.06,2026-10-01,L-2026-10-01,crm,2026-10-21 13:20:28,898b937fe7d0e57d,H-26534,prospect,1953-10-18
99970,199971,CT0099971,H-6881,A-31307,T08,2026-10-01,2027-09-30,12,803.62,2026-10-01,L-2026-10-01,crm,2026-10-21 13:20:28,1c73f2a0b351537e,H-6881,souscripteur,None
99973,199974,CT0099974,H-7765,0,T06,2026-10-01,2027-09-30,12,121.73,2026-10-01,L-2026-10-01,crm,2026-10-21 13:20:28,7b63e7dddf9892fd,H-7765,souscripteur,None
99977,199978,CT0099978,S-10059,A-11841,T09,2026-10-01,2028-09-30,24,827.90,2026-10-01,L-2026-10-01,crm,2026-10-21 13:20:28,39f09410ccaa3d3c,S-10059,souscripteur,None
99984,199985,CT0099985,S-14305,H-34640,T09,2026-10-01,2027-09-30,12,1068.48,2026-10-01,L-2026-10-01,crm,2026-10-21 13:20:28,c7a8d9b52dd86329,S-14305,souscripteur,None

In [9]:
#RQ-003 : téléphone du souscripteur renseigné :
souscripteurs = clients[
    clients["type_personne"].astype("string").str.strip().str.lower()
    == "souscripteur"
].copy()

telephone = souscripteurs["telephone"].astype("string")
ok = telephone.notna() & telephone.str.strip().ne("")

anomalies_RQ003 = controler(
    "RQ-003", "Téléphone renseigné", souscripteurs, ok, seuil=0.98
)

display(anomalies_RQ003)

RQ-003 - Téléphone renseigné
Lignes contrôlées : 49978
Anomalies : 5995
Conformité : 88.0%
Seuil respecté : False

,bronze_row_id,client_id,type_personne,nom,prenom,raison_sociale,date_naissance,adresse,cp,ville,pays,telephone,email,date_creation,_batch_id,_source_system,_ingested_at,_row_hash
13,100014,A-10011,souscripteur,None,None,Société Nicolas SARL,None,90 rue des Jardins,69500,Bron,FR,,contact@societenicolassarl9600.fr,2015-05-25,L-2026-10-01,crm,2026-10-21 13:20:04,3b1eaaf74ac86bbf
14,100015,A-10012,souscripteur,Fernandez,Leïla,None,1972-05-14,76 rue de l'Hôtel de Ville,69005,Lyon,FR,,leila.fernandez4365@gmail.com,2016-06-09,L-2026-10-01,crm,2026-10-21 13:20:04,a42e22ef8df32967
26,100027,A-10023,souscripteur,Fournier,Louise,None,1978-03-09,83 boulevard de la Liberté,42300,Roanne,FR,,louise.fournier9666@free.fr,2012-07-30,L-2026-10-01,crm,2026-10-21 13:20:04,3aead0de399321aa
36,100037,A-10032,souscripteur,Dubois,Olivier,None,1973-11-22,13 rue Nationale,01360,Loyettes,FR,,None,2012-02-06,L-2026-10-01,crm,2026-10-21 13:20:04,eccd02138d1b6b9f
46,100047,A-10041,souscripteur,Rousseau,Fabrice,None,1993-12-04,33 rue Jules Ferry,20200,Bastia,FR,,None,2019-12-20,L-2026-10-01,crm,2026-10-21 13:20:04,1bc6f40cd9a026da
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99869,199870,S-9869,souscripteur,Haddad,Christine,None,1949-03-03,54 rue Gambetta,74300,Cluses,FR,,christine.haddad4973@gmail.com,2013-07-04,L-2026-10-01,crm,2026-10-21 13:20:17,2a7fe5c0dc689d9c
99888,199889,S-9888,souscripteur,Dufour,Lucas,None,1976-02-05,81 rue Jules Ferry,01700,Miribel,FR,,lucas.dufour7755@laposte.net,2015-10-03,L-2026-10-01,crm,2026-10-21 13:20:17,b2963e0bc3d8276e
99889,199890,S-9889,souscripteur,François,Sébastien,None,2005-07-12,77 rue Léon Blum,69001,Lyon,FR,,None,2018-08-21,L-2026-10-01,crm,2026-10-21 13:20:17,aca288b35a55818e
99908,199909,S-9908,souscripteur,Muller,Christine,None,1961-03-20,108 rue de l'Hôtel de Ville,74200,Thonon-les-Bains,FR,,christine.muller9209@laposte.net,2013-07-08,L-2026-10-01,crm,2026-10-21 13:20:17,f05da692e5d0740e
99970,199971,S-9970,souscripteur,Haddad,Léa,None,1992-03-01,44 rue de la Mairie,74200,Thonon-les-Bains,FR,,lea.haddad4509@sfr.fr,2019-08-15,L-2026-10-01,crm,2026-10-21 13:20:17,1db88becf838800c

In [10]:
#RQ-005 : code postal français à 5 chiffres
france = clients[
    clients["pays"].astype("string").str.strip().str.upper().isin(["FR", "FRANCE"])
].copy()

cp = france["cp"].astype("string").str.strip()
ok = cp.str.fullmatch(r"\d{5}", na=False)

anomalies_RQ005 = controler(
    "RQ-005", "Code postal français à 5 chiffres", france, ok, seuil=0.98
)

display(anomalies_RQ005)

RQ-005 - Code postal français à 5 chiffres
Lignes contrôlées : 97037
Anomalies : 1478
Conformité : 98.48%
Seuil respecté : True

,bronze_row_id,client_id,type_personne,nom,prenom,raison_sociale,date_naissance,adresse,cp,ville,pays,telephone,email,date_creation,_batch_id,_source_system,_ingested_at,_row_hash
69,100070,A-10062,souscripteur,Lecomte,Christophe,None,1951-01-31,22 rue Victor Hugo,1500,Ambérieu-en-Bugey,FR,0690075277,None,2022-05-21,L-2026-10-01,crm,2026-10-21 13:20:04,913c8e4e0ec69589
105,100106,A-10095,prospect,Robin,Frédéric,None,1979-10-13,64 rue Jules Ferry,3100,Montluçon,FR,0606548492,contact@mecaniquemeuniersa5646.fr,2015-04-28,L-2026-10-01,crm,2026-10-21 13:20:04,a8652d8e78bc3ac4
196,100197,A-10178,prospect,Da Silva,Nicole,None,1947-04-25,56 rue de la Fontaine,1360,Bressolles,FR,None,nicole.dasilva3416@gmail.com,2021-03-17,L-2026-10-01,crm,2026-10-21 13:20:04,3e4f0517ae3a9593
209,100210,A-1019,assure,Leroux,Pierre,None,1974-03-11,67 rue Émile Zola,1700,Miribel,FR,0637251301,pierre.leroux6608@orange.fr,2018-10-19,L-2026-10-01,crm,2026-10-21 13:20:04,a2c7f32ec0335cdd
212,100213,A-10192,assure,Menard,Antoine,None,1974-08-04,40 allée des Tilleuls,1630,Saint-Genis-Pouilly,FR,0114872051,antoine.menard1979@free.fr,2016-10-30,L-2026-10-01,crm,2026-10-21 13:20:04,2a587a3b88edb1c7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99670,199671,S-9670,prospect,Haddad,David,None,1980-03-22,52 rue du Commerce,1000,Bourg-en-Bresse,FR,None,david.haddad8024@orange.fr,2015-02-01,L-2026-10-01,crm,2026-10-21 13:20:17,5e6663ea23a09faf
99807,199808,S-9807,souscripteur,Garcia,Marie,None,1953-05-22,69 boulevard Voltaire,1210,Ferney-Voltaire,FR,+33 7 19 28 48 46,marie.garcia1197@outlook.fr,2016-12-12,L-2026-10-01,crm,2026-10-21 13:20:17,a85352d2522f05e7
99858,199859,S-9858,assure,Colin,Manon,None,1951-10-30,12 chemin des Vignes,1200,Bellegarde-sur-Valserine,FR,04-16-76-75-45,None,2014-10-05,L-2026-10-01,crm,2026-10-21 13:20:17,ce70577e41be282f
99892,199893,S-9892,souscripteur,Lefèvre,Arthur,None,1951-09-11,8 boulevard Voltaire,9100,Pamiers,FR,0700028892,arthur.lefevre4805@sfr.fr,2021-06-24,L-2026-10-01,crm,2026-10-21 13:20:17,42240bf6a1720f39
99990,199991,S-9990,souscripteur,Roger,Aurélie,None,1964-08-25,70 rue du 8 Mai 1945,5000,Gap,FR,06 31 66 70 93,aurelie.roger9695@gmail.com,2020-11-04,L-2026-10-01,crm,2026-10-21 13:20:17,371d3af470944e7f

In [11]:
#RQ-009 : type de personne autorisé 
type_personne = clients["type_personne"].astype("string").str.strip().str.lower()
ok = type_personne.isin(["prospect", "souscripteur", "assure"])

anomalies_RQ009 = controler(
    "RQ-009", "Type de personne autorisé", clients, ok
)

display(anomalies_RQ009)

RQ-009 - Type de personne autorisé
Lignes contrôlées : 100000
Anomalies : 120
Conformité : 99.88%
Seuil respecté : False

,bronze_row_id,client_id,type_personne,nom,prenom,raison_sociale,date_naissance,adresse,cp,ville,pays,telephone,email,date_creation,_batch_id,_source_system,_ingested_at,_row_hash
218,100219,A-10198,client,Clément,Audrey,None,1983-10-17,112 rue Hoche,69600,Oullins,FR,0648905510,audrey.clement8259@gmail.com,2012-08-14,L-2026-10-01,crm,2026-10-21 13:20:04,0591ae5920c10439
771,100772,A-10700,prosp.,Lemaire,Patrick,None,1994-04-01,109 rue de la Fontaine,01600,Trévoux,FR,0633583400,patrick.lemaire8544@orange.fr,2019-06-15,L-2026-10-01,crm,2026-10-21 13:20:04,21c6b14751def481
827,100828,A-10751,assuré,Masson,Olivier,None,1945-07-22,47 rue Saint-Antoine,69130,Écully,FR,0386054548,olivier.masson1163@free.fr,2016-04-20,L-2026-10-01,crm,2026-10-21 13:20:04,5a34c9c32fe370cc
2518,102519,A-12289,assuré,Dubois,Raphaël,None,1952-06-13,19 rue de la Mairie,69007,Lyon,FR,06.26.64.04.04,raphael.dubois9514@gmail.com,2015-12-20,L-2026-10-01,crm,2026-10-21 13:20:04,0f061a58cfd24ad6
2976,102977,A-12705,assuré,None,None,Société Da Silva EURL,None,25 rue du 8 Mai 1945,69006,Lyon,FR,,contact@societedasilvaeurl1084.fr,2025-06-09,L-2026-10-01,crm,2026-10-21 13:20:04,7f2c30d17af662aa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98864,198865,S-8864,client,Lacroix,Leïla,None,1967-03-20,47 place de l'Église,69003,Lyon,FR,06.10.96.84.88,leila.lacroix7089@yahoo.fr,2013-12-02,L-2026-10-01,crm,2026-10-21 13:20:16,1125e1bde90a9d2e
99013,199014,S-9013,client,Martinez,Lucas,None,1991-01-14,7 route de Lyon,07100,Annonay,FR,0291782580,lucas.martinez4523@gmail.com,2015-06-12,L-2026-10-01,crm,2026-10-21 13:20:17,e47fc65a2307c21d
99413,199414,S-9413,client,Leroy,Rémi,None,1948-06-07,104 rue du Moulin,07200,Aubenas,FR,0651479304,remi.leroy4370@@orange.fr,2023-03-02,L-2026-10-01,crm,2026-10-21 13:20:17,7456c539204ecc9f
99808,199809,S-9808,client,François,Lucas,None,1996-08-29,2 avenue du Général de Gaulle,69001,Lyon,FR,,lucas.francois2092@laposte.net,2021-05-03,L-2026-10-01,crm,2026-10-21 13:20:17,df214a3ced78000c
99906,199907,S-9906,client,Rey,Jade,None,1966-10-05,65 rue de l'Hôtel de Ville,42700,Firminy,FR,0613762290,jade.rey645@sfr.fr,2015-03-25,L-2026-10-01,crm,2026-10-21 13:20:17,18403b19b7450a9e

In [12]:
#RQ-010 : durée de garantie autorisée
duree = pd.to_numeric(contrats["duree_garantie_mois"], errors="coerce")
ok = duree.isin([12, 24, 36, 60])

anomalies_RQ010 = controler(
    "RQ-010", "Durée de garantie autorisée", contrats, ok
)

display(anomalies_RQ010)

RQ-010 - Durée de garantie autorisée
Lignes contrôlées : 100000
Anomalies : 600
Conformité : 99.4%
Seuil respecté : False

,bronze_row_id,contrat_id,souscripteur_id,assure_id,code_type,date_debut,date_fin,duree_garantie_mois,prime_annuelle,date_derniere_cotisation,_batch_id,_source_system,_ingested_at,_row_hash
0,100001,CT0000001,A-18356,0,T02,2009-08-10,2019-08-09,120,615.15,2019-07-15,L-2026-10-01,crm,2026-10-21 13:20:19,12aa30fae234a6fd
1,100002,CT0000002,H-22766,H-28231,T07,2009-08-22,2019-08-21,120,237.93,2019-08-10,L-2026-10-01,crm,2026-10-21 13:20:19,c850ae6eae5a2a0f
2,100003,CT0000003,H-35362,H-26949,T05,2011-04-05,2021-04-04,120,411.58,2021-02-14,L-2026-10-01,crm,2026-10-21 13:20:19,60038bf9f8445d72
3,100004,CT0000004,A-28218,A-34217,T03,2012-09-23,2022-09-22,120,468.93,2022-09-18,L-2026-10-01,crm,2026-10-21 13:20:19,b990ae106c92c9ed
107,100108,CT0000108,S-13231,A-20063,T10,2014-03-12,2024-03-11,120,1698.24,None,L-2026-10-01,crm,2026-10-21 13:20:19,3ef19da40b58ef0b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99845,199846,CT0099846,S-3492,0,T11,2026-09-30,2028-03-29,18,1462.59,2026-09-30,L-2026-10-01,crm,2026-10-21 13:20:28,0bbb146bfaecb436
99880,199881,CT0099881,A-20422,0,T03,2026-10-01,2027-03-31,6,499.25,2026-10-01,L-2026-10-01,crm,2026-10-21 13:20:28,7a3aeace708bf4b4
99901,199902,CT0099902,A-3230,A-13424,T01,2026-10-01,2027-03-31,6,1167.10,None,L-2026-10-01,crm,2026-10-21 13:20:28,5a114f23f0908d5c
99903,199904,CT0099904,A-33307,S-25841,T02,2026-10-01,2028-03-31,18,500.18,2026-10-01,L-2026-10-01,crm,2026-10-21 13:20:28,205d05f01af46727
99964,199965,CT0099965,H-34488,0,T07,2026-10-01,2027-03-31,6,296.62,2026-10-01,L-2026-10-01,crm,2026-10-21 13:20:28,e935da30f8956c7c

In [13]:
#RQ-020 : identifiant technique unique et non nul
for nom, df in [("crm_client", clients), ("crm_contrat", contrats)]:
    cle = df["bronze_row_id"]
    ok = cle.notna() & ~cle.duplicated(keep=False)

    anomalies = controler(
        "RQ-020", f"Clé unique et non nulle : {nom}", df, ok
    )

    display(anomalies)

RQ-020 - Clé unique et non nulle : crm_client
Lignes contrôlées : 100000
Anomalies : 0
Conformité : 100.0%
Seuil respecté : True

Empty DataFrame
Columns: [bronze_row_id, client_id, type_personne, nom, prenom, raison_sociale, date_naissance, adresse, cp, ville, pays, telephone, email, date_creation, _batch_id, _source_system, _ingested_at, _row_hash]
Index: []

RQ-020 - Clé unique et non nulle : crm_contrat
Lignes contrôlées : 100000
Anomalies : 0
Conformité : 100.0%
Seuil respecté : True

Empty DataFrame
Columns: [bronze_row_id, contrat_id, souscripteur_id, assure_id, code_type, date_debut, date_fin, duree_garantie_mois, prime_annuelle, date_derniere_cotisation, _batch_id, _source_system, _ingested_at, _row_hash]
Index: []

In [14]:
print(f"Nombre de contrôles exécutés : {len(resultats)}")

Nombre de contrôles exécutés : 8

In [15]:
#verif 
display(pd.DataFrame(resultats))

,regle,description,lignes,anomalies,conformite_pct,seuil_respecte
0,RQ-001,Date de fin après date de début,100000,800,99.20,False
1,RQ-002,Souscripteur majeur au début du contrat,100000,8426,91.57,False
2,RQ-003,Téléphone renseigné,49978,5995,88.00,False
3,RQ-005,Code postal français à 5 chiffres,97037,1478,98.48,True
4,RQ-009,Type de personne autorisé,100000,120,99.88,False
5,RQ-010,Durée de garantie autorisée,100000,600,99.40,False
6,RQ-020,Clé unique et non nulle : crm_client,100000,0,100.00,True
7,RQ-020,Clé unique et non nulle : crm_contrat,100000,0,100.00,True

In [16]:
#Pièges repérés
souscripteurs = clients[
    clients["type_personne"].astype("string").str.strip().str.lower()
    == "souscripteur"
].copy()
telephone = souscripteurs["telephone"].astype("string")
nulls = telephone.isna()
vides = telephone.notna() & telephone.eq("")
blancs = telephone.notna() & telephone.str.strip().eq("") & ~vides
manquants_avant = int((nulls | vides | blancs).sum())
manquants_apres = int(telephone.str.strip().replace("", pd.NA).isna().sum())

pays_fr = clients["pays"].astype("string").str.strip().str.upper().isin(["FR", "FRANCE"])
cp = clients["cp"].astype("string").str.strip()
cp_valide = cp.str.fullmatch(r"\d{5}", na=False)
cp_invalides_tous = int((~cp_valide).sum())
cp_invalides_fr = int((pays_fr & ~cp_valide).sum())
etrangers_ignores = int((~pays_fr & ~cp_valide).sum())

pieges = pd.DataFrame([
    {
        "Règle": "RQ-003",
        "Piège": "Téléphone NULL, vide ou blanc",
        "Avant correction": f"{manquants_avant} manquants ({int(nulls.sum())} NULL, {int(vides.sum())} vides, {int(blancs.sum())} blancs)",
        "Après correction": f"{manquants_apres} restent à compléter après normalisation",
        "Preuve": "Le nettoyage ne remplace pas une donnée absente",
    },
    {
        "Règle": "RQ-005",
        "Piège": "Code postal étranger",
        "Avant correction": f"{cp_invalides_tous} codes invalides tous pays",
        "Après correction": f"{cp_invalides_fr} erreurs en France; {etrangers_ignores} cas étrangers écartés",
        "Preuve": "Le format français ne s'applique qu'aux adresses françaises",
    },
])
display(pieges)

,Règle,Piège,Avant correction,Après correction,Preuve
0,RQ-003,"Téléphone NULL, vide ou blanc","5995 manquants (2000 NULL, 1996 vides, 1999 bl...",5995 restent à compléter après normalisation,Le nettoyage ne remplace pas une donnée absente
1,RQ-005,Code postal étranger,2317 codes invalides tous pays,1478 erreurs en France; 839 cas étrangers écartés,Le format français ne s'applique qu'aux adress...

In [17]:

# US-11 : export des échecs et d'un échantillon 
echecs = []

for rule_id, donnees in [
    ("RQ-001", anomalies_RQ001),
    ("RQ-002", anomalies_RQ002),
    ("RQ-003", anomalies_RQ003),
    ("RQ-005", anomalies_RQ005),
    ("RQ-009", anomalies_RQ009),
    ("RQ-010", anomalies_RQ010),
]:
    copie = donnees.copy()
    copie["rule_id"] = rule_id
    echecs.append(copie)

echecs = pd.concat(echecs, ignore_index=True) if echecs else pd.DataFrame()

racine = Path.cwd()
if not (racine / "catalogue").is_dir():
    racine = racine.parent
dossier_catalogue = racine / "catalogue"
dossier_catalogue.mkdir(parents=True, exist_ok=True)

fichier_echecs = dossier_catalogue / "S2_US11_toutes_lignes_echec.csv"
echecs.to_csv(fichier_echecs, index=False, encoding="utf-8-sig")

regles_echantillon = echecs["rule_id"].value_counts().head(3).index
parts = [echecs[echecs["rule_id"].eq(rule_id)].head(7) for rule_id in regles_echantillon]
echantillon = pd.concat(parts, ignore_index=True).head(20)

familles = {
    "RQ-001": ("Cohérence des dates", "Date absente ou fin antérieure/égale au début", "Data Steward : vérifier les dates source"),
    "RQ-002": ("Validité de l'âge", "Âge insuffisant ou données de naissance manquantes", "Data Owner : vérifier l'éligibilité"),
    "RQ-003": ("Complétude du téléphone", "Téléphone NULL, vide ou blanc", "Data Steward : vérifier la donnée source"),
    "RQ-005": ("Format du code postal", "Code postal français mal formaté", "Data Steward : vérifier le format"),
    "RQ-009": ("Valeur hors domaine", "Type de personne non autorisé", "Data Owner : valider les valeurs autorisées"),
    "RQ-010": ("Durée de garantie", "Durée hors liste autorisée", "Data Owner : confirmer les durées autorisées"),
}

echantillon["famille_erreur"] = echantillon["rule_id"].map(lambda rule_id: familles[rule_id][0])
echantillon["cause_probable"] = echantillon["rule_id"].map(lambda rule_id: familles[rule_id][1])
echantillon["action_proposee"] = echantillon["rule_id"].map(lambda rule_id: familles[rule_id][2])

fichier_echantillon = dossier_catalogue / "S2_US11_echantillon_20_lignes.csv"
echantillon.to_csv(fichier_echantillon, index=False, encoding="utf-8-sig")

print("Lignes en échec :", len(echecs))
print("Règles dans l'échantillon :", echantillon["rule_id"].value_counts().to_dict())
print("Lignes dans l'échantillon :", len(echantillon))
print("Exports :", fichier_echecs, "et", fichier_echantillon)
display(echantillon)

Lignes en échec : 17419
Règles dans l'échantillon : {'RQ-002': 7, 'RQ-003': 7, 'RQ-005': 6}
Lignes dans l'échantillon : 20
Exports : /home/jovyan/work/catalogue/S2_US11_toutes_lignes_echec.csv et /home/jovyan/work/catalogue/S2_US11_echantillon_20_lignes.csv

,bronze_row_id,contrat_id,souscripteur_id,assure_id,code_type,date_debut,date_fin,duree_garantie_mois,prime_annuelle,date_derniere_cotisation,...,adresse,cp,ville,pays,telephone,email,date_creation,famille_erreur,cause_probable,action_proposee
0,100006,CT0000006,H-26653,0,T05,2014-01-02,2019-01-01,60,405.07,2018-12-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Data Owner : vérifier l'éligibilité
1,100015,CT0000015,S-2208,H-6365,T10,2014-01-04,2019-01-03,60,2016.27,2018-12-29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Data Owner : vérifier l'éligibilité
2,100022,CT0000022,A-30461,0,T02,2014-01-11,2019-01-10,60,676.09,2018-11-20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Data Owner : vérifier l'éligibilité
3,100031,CT0000031,H-97935,A-26914,T08,2014-01-23,2019-01-22,60,830.17,2018-11-29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Data Owner : vérifier l'éligibilité
4,100032,CT0000032,S-12190,S-25364,T09,2014-01-23,2019-01-22,60,740.13,2019-01-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Data Owner : vérifier l'éligibilité
5,100042,CT0000042,A-16083,A-37457,T04,2014-02-02,2019-02-01,60,1370.66,2018-12-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Data Owner : vérifier l'éligibilité
6,100046,CT0000046,S-97321,A-29620,T11,2014-02-03,2019-02-02,60,998.12,2019-01-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Data Owner : vérifier l'éligibilité
7,100014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,90 rue des Jardins,69500,Bron,FR,,contact@societenicolassarl9600.fr,2015-05-25,Complétude du téléphone,"Téléphone NULL, vide ou blanc",Data Steward : vérifier la donnée source
8,100015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,76 rue de l'Hôtel de Ville,69005,Lyon,FR,,leila.fernandez4365@gmail.com,2016-06-09,Complétude du téléphone,"Téléphone NULL, vide ou blanc",Data Steward : vérifier la donnée source
9,100027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,83 boulevard de la Liberté,42300,Roanne,FR,,louise.fournier9666@free.fr,2012-07-30,Complétude du téléphone,"Téléphone NULL, vide ou blanc",Data Steward : vérifier la donnée source
10,100037,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13 rue Nationale,01360,Loyettes,FR,,None,2012-02-06,Complétude du téléphone,"Téléphone NULL, vide ou blanc",Data Steward : vérifier la donnée source
11,100047,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33 rue Jules Ferry,20200,Bastia,FR,,None,2019-12-20,Complétude du téléphone,"Téléphone NULL, vide ou blanc",Data Steward : vérifier la donnée source
12,100118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,54 rue Victor Hugo,69008,Lyon,,,leila.morin4009@gmail.com,2017-08-25,Complétude du téléphone,"Téléphone NULL, vide ou blanc",Data Steward : vérifier la donnée source
13,100128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,71 avenue de la Libération,01360,Loyettes,FR,None,delphine.berger4578@orange.fr,2014-01-28,Complétude du téléphone,"Téléphone NULL, vide ou blanc",Data Steward : vérifier la donnée source
14,100070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22 rue Victor Hugo,1500,Ambérieu-en-Bugey,FR,0690075277,None,2022-05-21,Format du code postal,Code postal français mal formaté,Data Steward : vérifier le format
15,100106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,64 rue Jules Ferry,3100,Montluçon,FR,0606548492,contact@mecaniquemeuniersa5646.fr,2015-04-28,Format du code postal,Code postal français mal formaté,Data Steward : vérifier le format
16,100197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56 rue de la Fontaine,1360,Bressolles,FR,None,nicole.dasilva3416@gmail.com,2021-03-17,Format du code postal,Code postal français mal formaté,Data Steward : vérifier le format
17,100210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,67 rue Émile Zola,1700,Miribel,FR,0637251301,pierre.leroux6608@orange.fr,2018-10-19,Format du code postal,Code postal français mal formaté,Data Steward : vérifier le format
18,100213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40 allée des Tilleuls,1630,Saint-Genis-Pouilly,FR,0114872051,antoine.menard1979@free.fr,2016-10-30,Format du code postal,Code postal français mal formaté,Data Steward : vérifier le format
19,100228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,91 rue Molière,7110,Beaumont,FR,07 28 45 59 14,jean.lefebvre54@outlook.fr,2017-12-09,Format du code postal,Code postal français mal formaté,Data Steward : vérifier le format