Chargement & récupération

In [1]:
import pandas as pd
from pathlib import Path

racine = Path.cwd()
if not (racine / "catalogue").is_dir():
    racine = racine.parent
DOSSIER = racine / "catalogue"
DOSSIER.mkdir(parents=True, exist_ok=True)
FICHIER_ECHANTILLON = DOSSIER / "S2_US11_echantillon_20_lignes.csv"

for fichier in (FICHIER_ECHANTILLON,):
    if not fichier.exists():
        raise FileNotFoundError(
            f"Fichier introuvable : {fichier.resolve()}\n"
        )

echantillon = pd.read_csv(FICHIER_ECHANTILLON)
print("Lignes de l'échantillon chargées :", len(echantillon))
display(echantillon.head())

Lignes de l'échantillon chargées : 20

,bronze_row_id,contrat_id,souscripteur_id,assure_id,code_type,date_debut,date_fin,duree_garantie_mois,prime_annuelle,date_derniere_cotisation,...,adresse,cp,ville,pays,telephone,email,date_creation,famille_erreur,cause_probable,action_proposee
0,100006,CT0000006,H-26653,0,T05,2014-01-02,2019-01-01,60.0,405.07,2018-12-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Data Owner : vérifier l'éligibilité
1,100015,CT0000015,S-2208,H-6365,T10,2014-01-04,2019-01-03,60.0,2016.27,2018-12-29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Data Owner : vérifier l'éligibilité
2,100022,CT0000022,A-30461,0,T02,2014-01-11,2019-01-10,60.0,676.09,2018-11-20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Data Owner : vérifier l'éligibilité
3,100031,CT0000031,H-97935,A-26914,T08,2014-01-23,2019-01-22,60.0,830.17,2018-11-29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Data Owner : vérifier l'éligibilité
4,100032,CT0000032,S-12190,S-25364,T09,2014-01-23,2019-01-22,60.0,740.13,2019-01-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Data Owner : vérifier l'éligibilité

In [2]:
print('Lignes sélectionnées :', len(echantillon))
display(echantillon)

Lignes sélectionnées : 20

,bronze_row_id,contrat_id,souscripteur_id,assure_id,code_type,date_debut,date_fin,duree_garantie_mois,prime_annuelle,date_derniere_cotisation,...,adresse,cp,ville,pays,telephone,email,date_creation,famille_erreur,cause_probable,action_proposee
0,100006,CT0000006,H-26653,0,T05,2014-01-02,2019-01-01,60.0,405.07,2018-12-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Data Owner : vérifier l'éligibilité
1,100015,CT0000015,S-2208,H-6365,T10,2014-01-04,2019-01-03,60.0,2016.27,2018-12-29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Data Owner : vérifier l'éligibilité
2,100022,CT0000022,A-30461,0,T02,2014-01-11,2019-01-10,60.0,676.09,2018-11-20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Data Owner : vérifier l'éligibilité
3,100031,CT0000031,H-97935,A-26914,T08,2014-01-23,2019-01-22,60.0,830.17,2018-11-29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Data Owner : vérifier l'éligibilité
4,100032,CT0000032,S-12190,S-25364,T09,2014-01-23,2019-01-22,60.0,740.13,2019-01-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Data Owner : vérifier l'éligibilité
5,100042,CT0000042,A-16083,A-37457,T04,2014-02-02,2019-02-01,60.0,1370.66,2018-12-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Data Owner : vérifier l'éligibilité
6,100046,CT0000046,S-97321,A-29620,T11,2014-02-03,2019-02-02,60.0,998.12,2019-01-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Data Owner : vérifier l'éligibilité
7,100014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,90 rue des Jardins,69500.0,Bron,FR,NaN,contact@societenicolassarl9600.fr,2015-05-25,Complétude du téléphone,"Téléphone NULL, vide ou blanc",Data Steward : vérifier la donnée source
8,100015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,76 rue de l'Hôtel de Ville,69005.0,Lyon,FR,,leila.fernandez4365@gmail.com,2016-06-09,Complétude du téléphone,"Téléphone NULL, vide ou blanc",Data Steward : vérifier la donnée source
9,100027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,83 boulevard de la Liberté,42300.0,Roanne,FR,NaN,louise.fournier9666@free.fr,2012-07-30,Complétude du téléphone,"Téléphone NULL, vide ou blanc",Data Steward : vérifier la donnée source
10,100037,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13 rue Nationale,1360.0,Loyettes,FR,NaN,NaN,2012-02-06,Complétude du téléphone,"Téléphone NULL, vide ou blanc",Data Steward : vérifier la donnée source
11,100047,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33 rue Jules Ferry,20200.0,Bastia,FR,NaN,NaN,2019-12-20,Complétude du téléphone,"Téléphone NULL, vide ou blanc",Data Steward : vérifier la donnée source
12,100118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,54 rue Victor Hugo,69008.0,Lyon,NaN,,leila.morin4009@gmail.com,2017-08-25,Complétude du téléphone,"Téléphone NULL, vide ou blanc",Data Steward : vérifier la donnée source
13,100128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,71 avenue de la Libération,1360.0,Loyettes,FR,NaN,delphine.berger4578@orange.fr,2014-01-28,Complétude du téléphone,"Téléphone NULL, vide ou blanc",Data Steward : vérifier la donnée source
14,100070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22 rue Victor Hugo,1500.0,Ambérieu-en-Bugey,FR,0690075277,NaN,2022-05-21,Format du code postal,Code postal français mal formaté,Data Steward : vérifier le format
15,100106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,64 rue Jules Ferry,3100.0,Montluçon,FR,0606548492,contact@mecaniquemeuniersa5646.fr,2015-04-28,Format du code postal,Code postal français mal formaté,Data Steward : vérifier le format
16,100197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56 rue de la Fontaine,1360.0,Bressolles,FR,NaN,nicole.dasilva3416@gmail.com,2021-03-17,Format du code postal,Code postal français mal formaté,Data Steward : vérifier le format
17,100210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,67 rue Émile Zola,1700.0,Miribel,FR,0637251301,pierre.leroux6608@orange.fr,2018-10-19,Format du code postal,Code postal français mal formaté,Data Steward : vérifier le format
18,100213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40 allée des Tilleuls,1630.0,Saint-Genis-Pouilly,FR,0114872051,antoine.menard1979@free.fr,2016-10-30,Format du code postal,Code postal français mal formaté,Data Steward : vérifier le format
19,100228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,91 rue Molière,7110.0,Beaumont,FR,07 28 45 59 14,jean.lefebvre54@outlook.fr,2017-12-09,Format du code postal,Code postal français mal formaté,Data Steward : vérifier le format

In [3]:
familles = {
    'RQ-001': ('Cohérence des dates', 'Date absente ou date de fin antérieure ou égale au début', 'Vérifier les dates et les corriger après validation'),
    'RQ-002': ("Validité de l'âge", 'Âge insuffisant ou données de naissance manquantes', "Vérifier la date de naissance et l'âge au début du contrat"),
    'RQ-003': ('Complétude du téléphone', 'Téléphone NULL, vide ou composé d’espaces', 'Vérifier la source et compléter si possible'),
    'RQ-005': ('Format du code postal', 'Code postal français mal formaté', 'Vérifier et corriger le code postal'),
    'RQ-009': ('Valeur hors domaine', 'Type de personne non autorisé', 'Vérifier et corriger la valeur'),
    'RQ-010': ('Durée de garantie', 'Durée hors liste autorisée', 'Vérifier la durée et la corriger si nécessaire'),
}

def commentaire(rule_id, position):
    return familles.get(rule_id, ('À analyser', 'Cause à déterminer', 'Action à définir'))[position]

echantillon['famille_erreur'] = echantillon['rule_id'].map(lambda rule_id: commentaire(rule_id, 0))
echantillon['cause_probable'] = echantillon['rule_id'].map(lambda rule_id: commentaire(rule_id, 1))
echantillon['action_proposee'] = echantillon['rule_id'].map(lambda rule_id: commentaire(rule_id, 2))

echantillon['cause_confirmee'] = ''
echantillon['commentaire_analyse'] = ''

display(echantillon)

,bronze_row_id,contrat_id,souscripteur_id,assure_id,code_type,date_debut,date_fin,duree_garantie_mois,prime_annuelle,date_derniere_cotisation,...,ville,pays,telephone,email,date_creation,famille_erreur,cause_probable,action_proposee,cause_confirmee,commentaire_analyse
0,100006,CT0000006,H-26653,0,T05,2014-01-02,2019-01-01,60.0,405.07,2018-12-07,...,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Vérifier la date de naissance et l'âge au débu...,,
1,100015,CT0000015,S-2208,H-6365,T10,2014-01-04,2019-01-03,60.0,2016.27,2018-12-29,...,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Vérifier la date de naissance et l'âge au débu...,,
2,100022,CT0000022,A-30461,0,T02,2014-01-11,2019-01-10,60.0,676.09,2018-11-20,...,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Vérifier la date de naissance et l'âge au débu...,,
3,100031,CT0000031,H-97935,A-26914,T08,2014-01-23,2019-01-22,60.0,830.17,2018-11-29,...,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Vérifier la date de naissance et l'âge au débu...,,
4,100032,CT0000032,S-12190,S-25364,T09,2014-01-23,2019-01-22,60.0,740.13,2019-01-19,...,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Vérifier la date de naissance et l'âge au débu...,,
5,100042,CT0000042,A-16083,A-37457,T04,2014-02-02,2019-02-01,60.0,1370.66,2018-12-08,...,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Vérifier la date de naissance et l'âge au débu...,,
6,100046,CT0000046,S-97321,A-29620,T11,2014-02-03,2019-02-02,60.0,998.12,2019-01-16,...,NaN,NaN,NaN,NaN,NaN,Validité de l'âge,Âge insuffisant ou données de naissance manqua...,Vérifier la date de naissance et l'âge au débu...,,
7,100014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Bron,FR,NaN,contact@societenicolassarl9600.fr,2015-05-25,Complétude du téléphone,"Téléphone NULL, vide ou composé d’espaces",Vérifier la source et compléter si possible,,
8,100015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Lyon,FR,,leila.fernandez4365@gmail.com,2016-06-09,Complétude du téléphone,"Téléphone NULL, vide ou composé d’espaces",Vérifier la source et compléter si possible,,
9,100027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Roanne,FR,NaN,louise.fournier9666@free.fr,2012-07-30,Complétude du téléphone,"Téléphone NULL, vide ou composé d’espaces",Vérifier la source et compléter si possible,,
10,100037,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Loyettes,FR,NaN,NaN,2012-02-06,Complétude du téléphone,"Téléphone NULL, vide ou composé d’espaces",Vérifier la source et compléter si possible,,
11,100047,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Bastia,FR,NaN,NaN,2019-12-20,Complétude du téléphone,"Téléphone NULL, vide ou composé d’espaces",Vérifier la source et compléter si possible,,
12,100118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Lyon,NaN,,leila.morin4009@gmail.com,2017-08-25,Complétude du téléphone,"Téléphone NULL, vide ou composé d’espaces",Vérifier la source et compléter si possible,,
13,100128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Loyettes,FR,NaN,delphine.berger4578@orange.fr,2014-01-28,Complétude du téléphone,"Téléphone NULL, vide ou composé d’espaces",Vérifier la source et compléter si possible,,
14,100070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Ambérieu-en-Bugey,FR,0690075277,NaN,2022-05-21,Format du code postal,Code postal français mal formaté,Vérifier et corriger le code postal,,
15,100106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Montluçon,FR,0606548492,contact@mecaniquemeuniersa5646.fr,2015-04-28,Format du code postal,Code postal français mal formaté,Vérifier et corriger le code postal,,
16,100197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Bressolles,FR,NaN,nicole.dasilva3416@gmail.com,2021-03-17,Format du code postal,Code postal français mal formaté,Vérifier et corriger le code postal,,
17,100210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Miribel,FR,0637251301,pierre.leroux6608@orange.fr,2018-10-19,Format du code postal,Code postal français mal formaté,Vérifier et corriger le code postal,,
18,100213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Saint-Genis-Pouilly,FR,0114872051,antoine.menard1979@free.fr,2016-10-30,Format du code postal,Code postal français mal formaté,Vérifier et corriger le code postal,,
19,100228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Beaumont,FR,07 28 45 59 14,jean.lefebvre54@outlook.fr,2017-12-09,Format du code postal,Code postal français mal formaté,Vérifier et corriger le code postal,,

In [4]:
bilan = (
    echantillon.groupby(
        ["rule_id", "famille_erreur", "cause_probable", "action_proposee"],
        as_index=False,
    )
    .size()
    .rename(columns={
        "rule_id": "Règle",
        "famille_erreur": "Famille d'erreur",
        "cause_probable": "Cause probable",
        "action_proposee": "Action proposée (à qui ?)",
        "size": "Lignes",
    })
    .sort_values("Règle")
)
bilan["Lignes (sur 20)"] = bilan["Lignes"].map(lambda nombre: f"{nombre}/20")
bilan = bilan[["Règle", "Famille d'erreur", "Lignes (sur 20)", "Cause probable", "Action proposée (à qui ?)"]]
display(bilan)

,Règle,Famille d'erreur,Lignes (sur 20),Cause probable,Action proposée (à qui ?)
0,RQ-002,Validité de l'âge,7/20,Âge insuffisant ou données de naissance manqua...,Vérifier la date de naissance et l'âge au débu...
1,RQ-003,Complétude du téléphone,7/20,"Téléphone NULL, vide ou composé d’espaces",Vérifier la source et compléter si possible
2,RQ-005,Format du code postal,6/20,Code postal français mal formaté,Vérifier et corriger le code postal